### ISSUE TITLE
STY: Name of package

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-bids-pipeline#265]
I think we should rename `mne-study-template` to `mne-bids-pipeline`.

The "study template" name gives the wrong impression. When describing it to people I have to tell them it's a misnomer. I think from the implementation end we can make a redirect for mne.tools/mne-study-template and GitHub will automatically redirect when a repo gets renamed, so it's mostly a question of how many existing users we will annoy versus the benefits we will get from (I think much) better visibility from a more appropriate name. It seems worth it to me.

If people agree that renaming is worthwhile, does `mne-bids-pipeline` seem like a good choice? It seems most appropriate given the current tagline for the name is:

> The MNE Study Template is a full-flegded processing pipeline for your MEG and EEG data.
>
> It operates on raw data stored according to the Brain Imaging Data Structure (BIDS). Processing is controlled using a simple human-readable configuration file.

So `mne-bids-pipeline` to me captures the two essential components: being a pipeline, and working with BIDS data.

From offline discussion with @agramfort and @hoechenberger they're on board with a name change already. So people feel free to comment on `mne-bids-pipeline` specifically and/or give alternatives, or speak up if you're opposed to this move overall!

**Comment by jasmainak** [comment]
I'm not much involved here but I like it :)

**Comment by SophieHerbst** [comment]
I don't fully oversee which complications it might cause, but agree with @larsoner and I like mne-bids-pipeline!

**Comment by drammock** [comment]
+1 from me

**Comment by agramfort** [comment]
such a consensus on an MNE issue ❤

**Comment by larsoner** [comment]
I'll probably carry out the rename on Friday unless anyone objects in the meantime!

**Comment by hoechenberger** [comment]
MNE BIDS Pipeline is good. Should we move the repo to mne-tools/bids-pipeline?

Otherwise it might appear as an "MNE-BIDS Pipeline" (mind the hyphen), but that's sorta misleading...

**Comment by agramfort** [comment]
Keep mne

**Comment by larsoner** [comment]
I would call the repo `mne-bids-pipeline`, package `mne_bids_pipeline`, and write about it in docs as `MNE-BIDS-Pipeline` or `MNE BIDS Pipeline`. My preference is to have all hyphenated because it's most consistent with `MNE-Python`

**Comment by hoechenberger** [comment]
Ok!

**Comment by hoechenberger** [comment]
Clarification:

I'm ok with your proposal:

> I would call the repo `mne-bids-pipeline`, package `mne_bids_pipeline`, and write about it in docs as `MNE-BIDS-Pipeline`

I'm only slightly concerned that "MNE-BIDS-Pipeline" is rather longish … can we find a more concise or jazzy term than "pipeline"?

**Comment by hoechenberger** [comment]
How about … 

```
MNE-BIDS-Plumber
```
because, you know … pipeline … pipes … plumber?

![xx](https://user-images.githubusercontent.com/2046265/112453746-48072b80-8d58-11eb-8931-afb79e57927f.jpg)

**Comment by britta-wstnr** [comment]
MNE-Pypes :smile:

**Comment by larsoner** [comment]
I still prefer `MNE-BIDS-Pipeline` but could live with shortening it to `MNE-Pipeline` or so. I enjoy the more creative/clever names that avoid the word "pipeline" but so far don't prefer them because they hurt discoverability / make people have to think harder or read more about what the package actually does to know.

**Comment by dengemann** [comment]
I think pipeline is a misnomer, no? Isn't this supposed to be a template that is copied in each study and that extended? 
A pipeline would something that you use like a library.
```MNE-BIDS-template```, ```MNE-pipline-maker```, ```MNE-BIDS-maker```, ```MNE-BIDS-assistant``` ...

**Comment by drammock** [comment]
> I think pipeline is a misnomer, no?

I think it makes sense to call it a pipeline because it manages and performs several sequential preprocessing steps.

**Comment by hoechenberger** [comment]
> Isn't this supposed to be a template that is copied in each study and edited or extended according to the particular needs of the study?

In principle yes, but over the course of the past year we've moved more and more in the direction of a package-like thing as complexity grew.

I'll give my okay for `MNE-BIDS-Pipeline` :)

**Comment by agramfort** [comment]
>
> In principle yes, but over the course of the past year we've moved more
> and more in the direction of a package-like thing as complexity grew.
>
> I'll give my okay for MNE-BIDS-Pipeline :)
>
+1

I agree the code is now written and thought so that people will not just
clone, modify locally and keep changes locally.
We are moving towards a community consolidated pipeline

**Comment by hoechenberger** [comment]
@larsoner while you're breaking things anyway 😜 feel free to also rename the `master` branch to `main` if you want! We wanted to do that anyway

**Comment by larsoner** [comment]
I just had to fetch 500 MB to update my repo, which is not great. I think the `gh-pages` branch should be moved to another dedicated repo and deleted from here. @hoechenberger do you want to take care of that part? Maybe a new `mne-bids-pipeline-gh-pages` or something?

**Comment by agramfort** [comment]
I would stick to gh-pages but in this repo but I would squash commits
regularly. It's the simplest thing to do

**Comment by hoechenberger** [comment]
How come we're not running into this issue with MNE..?

**Comment by larsoner** [comment]
> I would stick to gh-pages but in this repo but I would squash commits

Should I start just by squashing all to a single commit now?

> How come we're not running into this issue with MNE..?

We use a separate repo for MNE-Python

https://github.com/mne-tools/mne-tools.github.io

**Comment by agramfort** [comment]
>
> Should I start just by squashing all to a single commit now?
>

+1


> How come we're not running into this issue with MNE..?
>
> We use a separate repo for MNE-Python
>
> https://github.com/mne-tools/mne-tools.github.io
>

yes but it's the URL of the org and it has a domain name.

if you don't use gh-pages maybe it could become

mne-bids-pipeline.mne.tools

but I prefer that we stick to:

mne.tools/mne-bids-pipeline

**Comment by sappelhoff** [comment]
>    I would stick to gh-pages but in this repo but I would squash commits

>> Should I start just by squashing all to a single commit now?

We are using a gh-pages branch in mne-bids too (235 commits by now) --> https://github.com/mne-tools/mne-bids/tree/gh-pages

so should we "squash" that too? 

I don't really get though why that would reduce the download size. Is the previous history of commits lost during squashing?

Is this something like `git rebase -i`, using `squash` for all but one of the commits? Would you mind posting your commands @larsoner, please ? :-)

**Comment by agramfort** [comment]
it's to avoid having to download all the web site versions when you git
clone the origin repo

>

**Comment by larsoner** [comment]
> I don't really get though why that would reduce the download size. Is the previous history of commits lost during squashing?

Yes squashing (and then push-force, which is what I did with this repo) loses the commit history. In MNE-Python `mne-tools.github.io` nowadays we do one huge squash at each release to keep repo size down while still maintaining some amount of history.

> Is this something like git rebase -i, using squash for all but one of the commits? Would you mind posting your commands @larsoner, please ? :-)

It was something like:
```
$ git fetch upstream
$ git checkout -b gh-pages upstream/gh-pages
$ git shortlog | wc -l
181
$ git rebase -i HEAD~181
... # do :%s/pick/squash/g in vim, then change the topmost one back to pick
```
