### ISSUE TITLE
UnboundLocal Exception

### ISSUE THREAD

**Issue by ktavabi** [mne-tools/mne-bids-pipeline#273]
> Traceback (most recent call last):
>   File "/Users/ktavabi/opt/miniconda3/envs/obiwan/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 431, in _process_worker
>     r = call_item()
>   File "/Users/ktavabi/opt/miniconda3/envs/obiwan/lib/python3.9/site-packages/joblib/externals/loky/process_executor.py", line 285, in __call__
>     return self.fn(*self.args, **self.kwargs)
>   File "/Users/ktavabi/opt/miniconda3/envs/obiwan/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 595, in __call__
>     return self.func(*args, **kwargs)
>   File "/Users/ktavabi/opt/miniconda3/envs/obiwan/lib/python3.9/site-packages/joblib/parallel.py", line 262, in __call__
>     return [func(*args, **kwargs)
>   File "/Users/ktavabi/opt/miniconda3/envs/obiwan/lib/python3.9/site-packages/joblib/parallel.py", line 262, in <listcomp>
>     return [func(*args, **kwargs)
>   File "/Users/ktavabi/Github/mne-study-template/scripts/01-import_and_maxfilter.py", line 338, in run_maxwell_filter
>     raw_out.save(raw_fname_out, picks=chs_to_include, overwrite=True,
>   File "<decorator-gen-170>", line 21, in save
>   File "/Users/ktavabi/Github/mne-python/mne/io/base.py", line 1405, in save
>     _write_raw(fname, self, info, picks, fmt, data_type, reset_range,
>   File "/Users/ktavabi/Github/mne-python/mne/io/base.py", line 1864, in _write_raw
>     use_fname = _construct_bids_filename(base, ext, part_idx)
>   File "/Users/ktavabi/Github/mne-python/mne/io/utils.py", line 309, in _construct_bids_filename
>     use_fname = '{}_split-{:02}_{}{}'.format(base, part_idx, modality, ext)
> UnboundLocalError: local variable 'modality' referenced before assignment
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/Users/ktavabi/Github/mne-study-template/config.py", line 1187, in wrapper
>     return func(*args, **kwargs)
>   File "/Users/ktavabi/Github/mne-study-template/scripts/01-import_and_maxfilter.py", line 420, in main
>     parallel(run_func(subject, session) for subject, session in
>   File "/Users/ktavabi/Github/mne-python/mne/parallel.py", line 128, in run
>     return fun(*args, **kwargs)
>   File "/Users/ktavabi/opt/miniconda3/envs/obiwan/lib/python3.9/site-packages/joblib/parallel.py", line 1054, in __call__
>     self.retrieve()
>   File "/Users/ktavabi/opt/miniconda3/envs/obiwan/lib/python3.9/site-packages/joblib/parallel.py", line 933, in retrieve
>     self._output.extend(job.get(timeout=self.timeout))
>   File "/Users/ktavabi/opt/miniconda3/envs/obiwan/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 542, in wrap_future_result
>     return future.result(timeout=timeout)
>   File "/Users/ktavabi/opt/miniconda3/envs/obiwan/lib/python3.9/concurrent/futures/_base.py", line 440, in result
>     return self.__get_result()
>   File "/Users/ktavabi/opt/miniconda3/envs/obiwan/lib/python3.9/concurrent/futures/_base.py", line 389, in __get_result
>     raise self._exception
> UnboundLocalError: local variable 'modality' referenced before assignment
>  /Users/ktavabi/opt/miniconda3/envs/obiwan/lib/python3.9/concurrent/futures/_base.py(389)__get_result()
>  raise self._exception
> 
>

**Comment by agramfort** [comment]
can you try to run without parallel and with debug so you can inspect the
crash in pdb
and try to figure out the issue? We can do a zoom call if you're stuck

>

**Comment by ktavabi** [comment]
Trying that now....
> 2021-03-31 09:21:11 INFO Now running: init_derivatives_dir
> 09:21:13 Using custom configuration: /Users/ktavabi/Github/Projects/paros-bids/paros_bids_config.py
> 09:21:14 [Step-01] Running: Initializing output directories.
> 09:21:14 [Step-01] Initializing output directories.
> 09:21:14 [Step-01] Completed: Initializing output directories.
> 2021-03-31 09:21:14 INFO Successfully finished running: init_derivatives_dir
> 2021-03-31 09:21:14 INFO Now running: import_and_maxfilter
> 09:21:14 [Step-01] Running Step 1: Data import
> 09:21:15 [Step-01][sub-007, ses-01] Loading reference run: 01.
> 09:21:18 [Step-01][sub-007, ses-01] Finding flat channels, and noisy channels using Maxwell filtering.
> 

But the rub is I can only get this far when I take out block of lns:1265-1268 of `noise_cov` checks in [pipeline configuration](https://github.com/mne-tools/mne-bids-pipeline/blob/6d1a0ffdba9396cbf34db322d95f6f1b190e34c0/config.py#L1265)

😕
I'd like to cash in that zoom get out of jail free card 🙏🏽... when's a good time?

Ps. this inevitably fails with yet another error I keep hitting on _random_ subjects...

> Traceback (most recent call last):
>   File "/Users/ktavabi/Github/mne-study-template/config.py", line 1458, in wrapper
>     return func(*args, **kwargs)
>   File "/Users/ktavabi/Github/mne-study-template/scripts/preprocessing/01-import_and_maxfilter.py", line 451, in main
>     parallel(run_func(subject, session) for subject, session in
>   File "/Users/ktavabi/Github/mne-study-template/scripts/preprocessing/01-import_and_maxfilter.py", line 451, in <genexpr>
>     parallel(run_func(subject, session) for subject, session in
>   File "/Users/ktavabi/Github/mne-study-template/scripts/preprocessing/01-import_and_maxfilter.py", line 373, in run_maxwell_filter
>     raw_out.save(raw_fname_out, picks=chs_to_include, overwrite=True,
>   File "<decorator-gen-170>", line 21, in save
>   File "/Users/ktavabi/Github/mne-python/mne/io/base.py", line 1405, in save
>     _write_raw(fname, self, info, picks, fmt, data_type, reset_range,
>   File "/Users/ktavabi/Github/mne-python/mne/io/base.py", line 1864, in _write_raw
>     use_fname = _construct_bids_filename(base, ext, part_idx)
>   File "/Users/ktavabi/Github/mne-python/mne/io/utils.py", line 309, in _construct_bids_filename
>     use_fname = '{}_split-{:02}_{}{}'.format(base, part_idx, modality, ext)
> UnboundLocalError: local variable 'modality' referenced before assignment
>  /Users/ktavabi/Github/mne-python/mne/io/utils.py(309)_construct_bids_filename()
>  use_fname = '{}_split-{:02}_{}{}'.format(base, part_idx, modality, ext) 

At this point I am not unconvinced I am 

- [ ] breaking conda environments
- [ ] breaking order of operations in the pipeline
- [ ] hallucinating
- [x] all of the above

**Comment by agramfort** [comment]
can you share just one subject with me?

>

**Comment by ktavabi** [comment]
[take your pick](https://www.dropbox.com/sh/dq2u6e6dxwwz7wg/AACy6JSMJO3V70_EXN9Vemk4a?dl=0)

**Comment by agramfort** [comment]
can you make sure the bids dataset you share passes the validator?

also can you put in the dropbox the config.py you used?

>

**Comment by ktavabi** [comment]
I am not sure exactly 
1. I renamed all my raw datasets 
2. CLI mne_bids raw_to_bids --subject_id subj007 --task lexicaldecision --allow_maxshield --raw subj007_lexicaldecision_meg-raw.fif --bids_root /Users/ktavabi/MEG/paros/bids
3. mne_bids report --bids_root /Users/ktavabi/MEG/paros/bids

> Summarizing participants.tsv /Users/ktavabi/MEG/paros/bids/participants.tsv...
> Summarizing scans.tsv files [PosixPath('/Users/ktavabi/MEG/paros/bids/sub-subj007/sub-subj007_scans.tsv')]...
> The participant template found: comprised of 1 men and 0 women;
> comprised of 1 right hand, 0 left hand and 0 ambidextrous; ages ranged from 17.0 to 17.0 (mean = 17.0, std = 0.0)
> ------------------------------------ REPORT ------------------------------------
> This dataset was created with BIDS version 1.4.0 by Please cite MNE-BIDS in your
> publication before removing this (citations in README). This report was
> generated with MNE-BIDS (https://doi.org/10.21105/joss.01896). The dataset
> consists of 1 participants (comprised of 1 men and 0 women; comprised of 1 right
> hand, 0 left hand and 0 ambidextrous; ages ranged from 17.0 to 17.0 (mean =
> 17.0, std = 0.0)). Data was recorded using a MEG system (Elekta manufacturer)
> sampled at 2000.0 Hz with line noise at 60.0 Hz. There was 1 scan in total.
> Recording durations ranged from 740.25 to 740.25 seconds (mean = 740.25, std =
> 0.0), for a total of 740.25 seconds of data recorded over all scans. For each
> dataset, there were on average 332.0 (std = 0.0) recording channels per scan,
> out of which 332.0 (std = 0.0) were used in analysis (0.0 +/- 0.0 were removed
> from analysis).

**Comment by ktavabi** [comment]
Thanks for your time @agramfort @hoechenberger original dataset naming had issues, should've renamed them initially.

**Comment by ktavabi** [comment]
@agramfort is there an explicit `validator`? I've done the following with CLI

1. `mne_bids raw_to_bids --subject_id subj007 --task lexicaldecision --allow_maxshield --raw subj007_lexicaldecision_meg-raw.fif --bids_root .../test`
3. `mne_bids report` on the entire dataset returned

> ------------------------------------ REPORT ------------------------------------
> This dataset was created with BIDS version 1.4.0 by Please cite MNE-BIDS in your
> publication before removing this (citations in README). This report was
> generated with MNE-BIDS (https://doi.org/10.21105/joss.01896). The dataset
> consists of 37 participants (comprised of 38 men and 0 women; comprised of 38
> right hand, 0 left hand and 0 ambidextrous; ages ranged from 16.0 to 18.0 (mean
> = 16.97, std = 0.28))and 1 recording sessions: 01. Data was recorded using a MEG
> system (Elekta manufacturer) sampled at 2000.0 Hz with line noise at 60 Hz.
> There were 66 scans in total. Recording durations ranged from 713.25 to 761.25
> seconds (mean = 741.71, std = 9.64), for a total of 27443.23 seconds of data
> recorded over all scans. For each dataset, there were on average 332.0 (std =
> 0.0) recording channels per scan, out of which 332.0 (std = 0.0) were used in
> analysis (0.0 +/- 0.0 were removed from analysis).

4. `python  ~/Github/mne-study-template/run.py all --config ~/Github/Projects/paros-bids/paros_bids_config.py`

> Traceback (most recent call last):
>   File "/Users/ktavabi/Github/mne-study-template/config.py", line 1458, in wrapper
>     return func(*args, **kwargs)
>   File "/Users/ktavabi/Github/mne-study-template/scripts/preprocessing/01-import_and_maxfilter.py", line 451, in main
>     parallel(run_func(subject, session) for subject, session in
>   File "/Users/ktavabi/Github/mne-study-template/scripts/preprocessing/01-import_and_maxfilter.py", line 451, in <genexpr>
>     parallel(run_func(subject, session) for subject, session in
>   File "/Users/ktavabi/Github/mne-study-template/scripts/preprocessing/01-import_and_maxfilter.py", line 373, in run_maxwell_filter
>     raw_out.save(raw_fname_out, picks=chs_to_include, overwrite=True,
>   File "<decorator-gen-170>", line 21, in save
>   File "/Users/ktavabi/Github/mne-python/mne/io/base.py", line 1405, in save
>     _write_raw(fname, self, info, picks, fmt, data_type, reset_range,
>   File "/Users/ktavabi/Github/mne-python/mne/io/base.py", line 1864, in _write_raw
>     use_fname = _construct_bids_filename(base, ext, part_idx)
>   File "/Users/ktavabi/Github/mne-python/mne/io/utils.py", line 309, in _construct_bids_filename
>     use_fname = '{}_split-{:02}_{}{}'.format(base, part_idx, modality, ext)
> UnboundLocalError: local variable 'modality' referenced before assignment
> > /Users/ktavabi/Github/mne-python/mne/io/utils.py(309)_construct_bids_filename()
> -> use_fname = '{}_split-{:02}_{}{}'.format(base, part_idx, modality, ext)

**Comment by ktavabi** [comment]
@agramfort it looks like _after_ max filtering `deconstructed_base` in `/mne/io/utils.py(309)_construct_bids_filename()`
doesn't contain any of `bids_supported = ['meg', 'eeg', 'ieeg']` values...

> (Pdb) deconstructed_base
> ['/Users/ktavabi/MEG/paros/bids/derivatives/mne-bids-pipeline/sub-007/meg/sub-007', 'task-lexicaldecision', 'proc-sss', 'raw']

Ps. is there an explicit _validator_ function somewhere in the suite?

**Comment by agramfort** [comment]
see https://bids-standard.github.io/bids-validator/
https://github.com/bids-standard/bids-validator

>

**Comment by ktavabi** [comment]
Mother of God! This is turtles all the way down.

**Comment by hoechenberger** [comment]
> Thanks for your time @agramfort @hoechenberger original dataset naming had issues, should've renamed them initially.

Very interesting still, we shouldn't fail like this …

**Comment by ktavabi** [comment]
> Very interesting still, we shouldn't fail like this …

You're right, this has been rather painful. @hoechenberger let me [buy you a coffee](https://www.buymeacoffee.com)

**Comment by ktavabi** [comment]
Say what now? 😑

![image](https://user-images.githubusercontent.com/4381290/113448687-2853b100-93b1-11eb-88de-2b9fc8bc521d.png)

ugh 😩

> 2021-04-02 12:23:40 INFO Now running: init_derivatives_dir
> 12:23:48 Using custom configuration: /Users/ktavabi/Github/Projects/paros-bids/paros_bids_config.py
> 12:23:48 [Step-01] Running: Initializing output directories.
> 12:23:48 [Step-01] Initializing output directories.
> 12:23:48 [Step-01] Completed: Initializing output directories.
> 2021-04-02 12:23:48 INFO Successfully finished running: init_derivatives_dir
> 2021-04-02 12:23:48 INFO Now running: import_and_maxfilter
> 12:23:51 [Step-01] Running Step 1: Data import
> 12:23:52 [Step-01][sub-007] Loading reference run: None.
> 12:23:57 [Step-01][sub-007] Finding flat channels, and noisy channels using Maxwell filtering.
> 12:25:05 [Step-01][sub-007] Found 3 flat channels.
> 12:25:05 [Step-01][sub-007] Found 0 noisy channels.
> 12:25:05 [Step-01][sub-007] Marked 3 channels as bad.
> 12:25:05 [Step-01][sub-007] Applying Maxwell filter to experimental data.
> 12:25:05 [Step-01][sub-007]     st_duration=10
> 12:26:22  A critical error occurred.
> Traceback (most recent call last):
>   File "/Users/ktavabi/Github/mne-study-template/config.py", line 1458, in wrapper
>     return func(*args, **kwargs)
>   File "/Users/ktavabi/Github/mne-study-template/scripts/preprocessing/01-import_and_maxfilter.py", line 451, in main
>     parallel(run_func(subject, session) for subject, session in
>   File "/Users/ktavabi/Github/mne-study-template/scripts/preprocessing/01-import_and_maxfilter.py", line 451, in <genexpr>
>     parallel(run_func(subject, session) for subject, session in
>   File "/Users/ktavabi/Github/mne-study-template/scripts/preprocessing/01-import_and_maxfilter.py", line 373, in run_maxwell_filter
>     raw_out.save(raw_fname_out, picks=chs_to_include, overwrite=True,
>   File "<decorator-gen-170>", line 21, in save
>   File "/Users/ktavabi/Github/mne-python/mne/io/base.py", line 1405, in save
>     _write_raw(fname, self, info, picks, fmt, data_type, reset_range,
>   File "/Users/ktavabi/Github/mne-python/mne/io/base.py", line 1864, in _write_raw
>     use_fname = _construct_bids_filename(base, ext, part_idx)
>   File "/Users/ktavabi/Github/mne-python/mne/io/utils.py", line 309, in _construct_bids_filename
>     use_fname = '{}_split-{:02}_{}{}'.format(base, part_idx, modality, ext)
> UnboundLocalError: local variable 'modality' referenced before assignment
> > /Users/ktavabi/Github/mne-python/mne/io/utils.py(309)_construct_bids_filename()
> -> use_fname = '{}_split-{:02}_{}{}'.format(base, part_idx, modality, ext)
> (Pdb) p deconstructed_base
> ['/Users/ktavabi/MEG/derivatives/mne-bids-pipeline/sub-007/meg/sub-007', 'task-lexicaldecision', 'proc-sss', 'raw']
> (Pdb) 
>

**Comment by agramfort** [comment]
It’s ok. It should not be a Pb for the pipeline

**Comment by ktavabi** [comment]
I'll update Dropbox data later today. 

PS you want to author up? You lay down the ML stats, and I the speculation?

**Comment by larsoner** [comment]
@ktavabi are you on 0.22 / 0.22.1? if so I would try latest MNE-Python `main` and see if it fixes things, as your traceback has:
```
File "/Users/ktavabi/Github/mne-python/mne/io/utils.py", line 309, in _construct_bids_filename
use_fname = '{}split-{:02}{}{}'.format(base, part_idx, modality, ext)
```
but line 309+ in `mne/io/utils.py` is:
```
    modality = deconstructed_base[-1]
    base = '_'.join(deconstructed_base[:-1])
    use_fname = '{}_split-{:02}_{}{}'.format(base, part_idx, modality, ext)
    if dirname:
        use_fname = op.join(dirname, use_fname)
    return use_fname
```
I suspect it was fixed in https://github.com/mne-tools/mne-python/pull/8478

**Comment by ktavabi** [comment]
Onwards & up! Thanks all.
