### ISSUE TITLE
Failure with NoneType covariance object

### ISSUE THREAD

**Issue by ktavabi** [mne-tools/mne-bids-pipeline#279]
Should there be a check for empty projectors before trying to write?

https://github.com/mne-tools/mne-bids-pipeline/blob/92f6dcb8f0bcb4f848823513b39af87c21224c04/scripts/preprocessing/04b-run_ssp.py#L74

```
(Pdb) p ecg_projs
None
```

**Comment by agramfort** [comment]
how can i replicate?

>

**Comment by hoechenberger** [comment]
I'd say that's either an implementation or a documentation bug upstream in MNE-Python, because the docstring says:

```python
    Returns
    -------
    proj : list
        Computed SSP projectors.
    ecg_events : ndarray
        Detected ECG events.
    drop_log : list
        The drop log, if requested.
```
So in case of no projectors, we should get back an empty list

**Comment by hoechenberger** [comment]
I've looked at the MNE code and I don't see how we could end up with `None` here … So I'd like to second @agramfort's request for a how to replicate this :)

**Comment by larsoner** [comment]
Beware the short-circuit:

https://github.com/mne-tools/mne-python/blob/5ae29cd69aa6075dc9ecd97402571ff7b2a03d21/mne/preprocessing/ssp.py#L70-L73

Not sure if we should update the docstring (doc) or behavior (bug)

**Comment by hoechenberger** [comment]
> Beware the short-circuit:

Wow, I missed that one! 🤦 

Would anyone ever need to be able to tell apart whether no **event** was found vs no **projector** could be generated? If not, we should return an empty list here too…

**Comment by larsoner** [comment]
I think from that point onward we should be guaranteed to get `n_proj` projectors back. So I think returning an empty list and calling it a bugfix in MNE-Python is fine. But in mne-bids-pipeline we probably want to check that we got back the number of projectors that we requested and if not, raise an error. It's indicative that something in the pipeline needs to be fixed (e.g., removing large noisy ECG segments, changing `reject` criteria, etc.). I think the warning emitted by MNE-Python is not enough

**Comment by hoechenberger** [comment]
@ktavabi This should be fixed now, could you please pull `main` of both `mne-python` and `mne-bids-pipeline` and see if it works for you?

**Comment by ktavabi** [comment]
Looks fixed to me. Hope I wake up to a bunch of reports! Thanks all.

**Comment by hoechenberger** [comment]
Perfect! Fingers crossed 🤞😅
