### ISSUE TITLE
subjects_list in config.py ignored

### ISSUE THREAD

**Issue by MerlinDumeur** [mne-tools/mne-bids-pipeline#284]
Hello,

I am trying to run the pipeline on a subset of the subjects of the ds00339 dataset, but no matter what I set subjects list as, it is run on all subjects of the dataset. 

I use the latest version of this repo, and I copied the config file used for testing: https://github.com/mne-tools/mne-bids-pipeline/blob/main/tests/configs/config_ds003392.py
The dataset was downloaded from OpenNeuro.

I am not sure where to start debugging this, or if I missed an obvious step so I am asking here.

**Comment by hoechenberger** [comment]
Hi, I will look into this and get back to you.

**Comment by hoechenberger** [comment]
The configuration option is actually called `subjects` now, we need to update the example config files.

**Comment by agramfort** [comment]
we just fixed it together

>

**Comment by MerlinDumeur** [comment]
thanks for the help!

**Comment by MerlinDumeur** [comment]
Also, maybe a mention that it is the main branch version of mne that is needed in the documentation would be nice
