### ISSUE TITLE
Config error when specifying no high-pass filtering on the raw data

### ISSUE THREAD

**Issue by MerlinDumeur** [mne-tools/mne-bids-pipeline#285]
The checks to make sure ica_l_freq < l_freq does not take into account the possibility where l_freq is None.

The code fails on these checks: 
- https://github.com/mne-tools/mne-bids-pipeline/blob/0c67af9e7587bf6639def22c553e0eb64927b371/config.py#L1306
- https://github.com/mne-tools/mne-bids-pipeline/blob/0c67af9e7587bf6639def22c553e0eb64927b371/scripts/preprocessing/04a-run_ica.py#L72
- https://github.com/mne-tools/mne-bids-pipeline/blob/0c67af9e7587bf6639def22c553e0eb64927b371/scripts/preprocessing/04a-run_ica.py#L75

both when l_freq is None and ica_l_freq > 0 (expected to raise an error but currently the error is a TypeError), and when l_freq and ica_l_freq are both None.

This can be reproduced by setting l_freq and ica_l_freq to None in the config file.

I don't know what the best practice is: I want to estimate the low-frequency power spectrum, so I can't have my data high-passed. However I'm not sure it is a good idea to run the ICA with no high-pass filter.
I was able to get the code running with a few modifications, but I don't know if I should include highpass filtering for the ICA or not.

**Comment by hoechenberger** [comment]
Thanks for reporting this! We should check whether `config.l_freq` or `config.ica_l_freq` are `None` before doing the comparisons.



> However I'm not sure it is a good idea to run the ICA with no high-pass filter.

It's not a good idea, you need to remove those slow drifts, otherwise ICA will have a bad time.

So you'd want to e.g. use

```python
l_freq = 0.1
ica_l_freq = 1
```

**Comment by MerlinDumeur** [comment]
I'm working on a project where I need to estimate the power spectrum well below 1 Hz so I really cannot afford to highpass filter the raw data.

Would this work?
```python
l_freq = None
ica_l_freq = 1
```

**Comment by SophieHerbst** [comment]
In the 'old' version, we just high-pass filtered the raw and created new epochs_for_ica, independently from the hp applied to the data: https://github.com/brainthemind/CogBrainDyn_MEG_Pipeline/blob/master/05a-run_ica.py
Would that still work, @hoechenberger?

**Comment by hoechenberger** [comment]
> Would that still work, @hoechenberger?

We either re-use the existing raw (irrespective if filtered or not) and apply another high-pass filter (`ica_l_freq`) before generating epochs for ICA.

So `l_freq=None, ica_l_freq=1` would work too, yes
