### ISSUE TITLE
`ERROR: Could not consume arg: freesurfer` when finishing `run.py freesurfer`

### ISSUE THREAD

**Issue by MerlinDumeur** [mne-tools/mne-bids-pipeline#295]
Here is the output from running `run.py freesurfer`:
```
2021-04-15 17:02:00 INFO Now running: init_derivatives_dir
17:02:01 Using custom configuration: /home/merlin/hMT+/config.py
17:02:01 [Step-01] Running: Initializing output directories.
17:02:01 [Step-01] Initializing output directories.
17:02:01 [Step-01] Completed: Initializing output directories.
2021-04-15 17:02:01 INFO Successfully finished running: init_derivatives_dir
2021-04-15 17:02:01 INFO Now running: recon_all
17:02:01 Running FreeSurfer
17:02:01 Running recon-all on subject 01. This will take a LONG time – it's a good idea to let it run over night.
17:02:01 Subject 01 is already present. Please delete the directory if you want to recompute.
ERROR: Could not consume arg: freesurfer
Usage: recon_all.py freesurfer

```
Here I only ask to process subject 01, which was already done.
Even though there was no error within `recon_all.py` (which I checked using a print at the end of `main`), the script exits with an error.
The problem seems to be coming from using both Fire and runpy: https://github.com/mne-tools/mne-bids-pipeline/blob/d49d05351b2da2a4269dff5761a457e0e85964bd/run.py#L98
it seems Fire expects all arguments to be used for both `run.py` and `recon_all.py`, when they are only used for `run.py`.

Note that this is not a regression from #289, as it happens even without that modification.

I'm not sure how fix this, maybe it is simple though as it does not seem to be a problem for other scripts.

**Comment by hoechenberger** [comment]
> 17:02:01 Running recon-all on subject 01. This will take a LONG time – it's a good idea to let it run over night.
> 17:02:01 Subject 01 is already present. Please delete the directory if you want to recompute.

Does the problem also occur if you remove the existing surfaces?

**Comment by MerlinDumeur** [comment]
If I remove the existing subject the code runs properly, but it takes a long time and I haven't had the time to run it to the end yet, as it crashed due to some problems with linking fsaverage. 
That should be solved now though, and I will report as soon as my current run is done.

**Comment by MerlinDumeur** [comment]
I do have the same issue after deleting the existing subjects:

```
(mne-bids) merlin@Everchange:~/PhD/mne-bids-pipeline$ python run.py freesurfer --config=~/hMT+/config.py --n_jobs=4
2021-04-15 17:22:34 INFO Now running: init_derivatives_dir
17:22:34 Using custom configuration: /home/merlin/hMT+/config.py
17:22:34 [Step-01] Running: Initializing output directories.
17:22:34 [Step-01] Initializing output directories.
17:22:34 [Step-01] Completed: Initializing output directories.
2021-04-15 17:22:34 INFO Successfully finished running: init_derivatives_dir
2021-04-15 17:22:34 INFO Now running: recon_all
17:22:34 Running FreeSurfer
ERROR: Could not consume arg: freesurfer
Usage: recon_all.py freesurfer

For detailed information on this command, run:
  recon_all.py freesurfer --help
```

When setting `n_jobs` > 1 there is no output, however I know the freesurfer recon-all command was executed properly based on the log files.

**Comment by hoechenberger** [comment]
Very interesting, especially since it only occurs after (successfully!) running FreeSurfer…

**Comment by agramfort** [comment]
Yes when I wrote this file I saw that stdout from freesurfer was not shown.
But it does not mean it's not working.

>

**Comment by MerlinDumeur** [comment]
The output not showing is not the problem here, it's that successful execution of the script results in an error, which might be confusing.

I'm guessing it's because the decorator `failsafe_run` is not used in `recon_all.py`.

**Comment by MerlinDumeur** [comment]
> I'm guessing it's because the decorator failsafe_run is not used in recon_all.py.

After some testing, it does not appear to be the case.
Might be because the main fuction takes an argument, when for the other scripts it is not the case?

**Comment by agramfort** [comment]
let us know if you go to the bottom of this. thx

>

**Comment by hoechenberger** [comment]
I'll look into this tonight

**Comment by hoechenberger** [comment]
… I'm delayed, sorry. But this is on my agenda for today.
