### ISSUE TITLE
Add interactive / single subject mode ? 

### ISSUE THREAD

**Issue by SophieHerbst** [mne-tools/mne-bids-pipeline#3]
For beginners and anyone who needs to check their data and debug I would find it really helpful to add an interactive mode for the scripts. 
I usually do 
```
figure = raw.plot(n_channels = 50,butterfly=True, group_by='position') 
``` 
just after importing to check for bad sensors again. 
Then, I plot events, single trial epochs, ICA components, ... 
The report might be a bit overwhelming for newbies. What do you think?

**Comment by agramfort** [comment]
yes we should add a verbose mode that shows figures

and document how to work interactively by putting a breakpoint
and how to run a single subject for one script.

>

**Comment by SophieHerbst** [comment]
Will do the plotting mode. Any suggestions on how to? 
Just add something like plot_mode = True to each individual script?

**Comment by agramfort** [comment]
plot=True 

In functions?

We should allow to show or not and savefigs to disk. But one thing at a time

**Comment by SophieHerbst** [comment]
what does 
> In functions 

mean?

**Comment by agramfort** [comment]
Thinking about it using a config parameter sounds simpler. Clear?

**Comment by SophieHerbst** [comment]
Yes. Ok, I will put it in the config then.
Is it ok if I merge the other pull request before? Just afraid to get lost in branches otherwise.

**Comment by agramfort** [comment]
Yes merge

**Comment by SophieHerbst** [comment]
The plotting is there for the first scripts, needs to be added for the later ones. 
I am not sure what is the best way to suggest for debugging the scripts, since it depends on the editor used.

**Comment by agramfort** [comment]
can you put breakpoints with spyder?

**Comment by larsoner** [comment]
I think nowadays we have `--interactive=1` so I'll close this. But @SophieHerbst if this doesn't get you the plots you want, feel free to reopen with what else would be useful and we can add more interaction points
