### ISSUE TITLE
Issue when eog_channels = None

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#310]
@dnacombo today ran into an issue related incorrect handling of an `eog_channels = None` setting in the configuration file. I don't remember the details; opening this issue so we don't forget about this.

**Comment by dnacombo** [comment]
What I remember was that we set `eog_channels = None` and `eeg_bipolar_channels = ['somestuff']` and expected that 'somestuff' was taken as eog, which it wasn't.
after setting `eog_channels = ['somestuff']`, it was all fixed.
So not sure that it was an issue, actually.
