### ISSUE TITLE
Cannot use both SSP and ICA

### ISSUE THREAD

**Issue by guiomar** [mne-tools/mne-bids-pipeline#314]
Hi!

When marking `use_uca=true` I get this error: 

> Cannot use both SSP and ICA.

The `use_ssp` field is not declared in the config file (as the default is false)

Could I be doing something wrong? Would you mind trying to reproduce?

**Comment by agramfort** [comment]
can you replicate the issue with some public data so we can easily
replicate?
if so please share also your config.py file.

otherwise share a dropbox folder with me please

**Comment by guiomar** [comment]
Yes, I used ds000248, wit this config file:

> 
> bids_root = '../6089740e02bc8861a590b94b/bids/.'
> deriv_root = 'out_dir'
> subjects = ['01']
> runs = ['01']
> find_flat_channels_meg = False
> find_noisy_channels_meg = False
> use_maxwell_filter = False
> fix_stim_artifact = False
> h_freq = 40
> decim = 10
> on_rename_missing_events = 'raise'
> event_repeated = 'error'
> conditions = ['Auditory', 'Visual', 'Auditory/Left', 'Auditory/Right'] 
> contrasts = [('Visual', 'Auditory'),('Auditory/Right', 'Auditory/Left')]
> use_ica = True
> ica_algorithm = 'picard'
> ch_types = ['meg']

**Comment by guiomar** [comment]
oh! I realized the use_ssp if True by default! SORRY

**Comment by guiomar** [comment]
I really apologize for all these absurd questions. I'm getting used now to python and mne tool (which I'm finding awesome). Thanks for your patience!

**Comment by agramfort** [comment]
no problem

**Comment by agramfort** [comment]
don't worry :)

**Comment by hoechenberger** [comment]
@agramfort I’m starting to think we should set both, ICA and SSP, to False by default. WDYT?

**Comment by agramfort** [comment]
Yes agreed

**Comment by guiomar** [comment]
Yes, I also think it might be more intuitive, since all the other booleans are false by default
