### ISSUE TITLE
TypeError

### ISSUE THREAD

**Issue by ktavabi** [mne-tools/mne-bids-pipeline#317]
Tried running previously working config with modified `reject = dict(mag=3000e-15, grad=3000e-13)` parameter after pulling upstream and got this error:

> 
> Traceback (most recent call last):
>   File "/Users/ktavabi/Github/mne-study-template/run.py", line 200, in <module>
>     fire.Fire(process)
>   File "/Users/ktavabi/opt/miniconda3/envs/obiwan/lib/python3.9/site-packages/fire/core.py", line 141, in Fire
>     component_trace = _Fire(component, args, parsed_flag_args, context, name)
>   File "/Users/ktavabi/opt/miniconda3/envs/obiwan/lib/python3.9/site-packages/fire/core.py", line 466, in _Fire
>     component, remaining_args = _CallAndUpdateTrace(
>   File "/Users/ktavabi/opt/miniconda3/envs/obiwan/lib/python3.9/site-packages/fire/core.py", line 681, in _CallAndUpdateTrace
>     component = fn(*varargs, **kwargs)
>   File "/Users/ktavabi/Github/mne-study-template/run.py", line 195, in process
>     _run_script(script_path, config, root_dir, subject, session, task, run)
>   File "/Users/ktavabi/Github/mne-study-template/run.py", line 101, in _run_script
>     runpy.run_path(script_path, run_name='__main__')
>   File "/Users/ktavabi/opt/miniconda3/envs/obiwan/lib/python3.9/runpy.py", line 268, in run_path
>     return _run_module_code(code, init_globals, run_name,
>   File "/Users/ktavabi/opt/miniconda3/envs/obiwan/lib/python3.9/runpy.py", line 97, in _run_module_code
>     _run_code(code, mod_globals, init_globals,
>   File "/Users/ktavabi/opt/miniconda3/envs/obiwan/lib/python3.9/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/Users/ktavabi/Github/mne-study-template/scripts/init/00-init_derivatives_dir.py", line 9, in <module>
>     import config
>   File "/Users/ktavabi/Github/mne-study-template/config.py", line 1530, in <module>
>     reject: Optional[Dict[str, float]],
>   File "/Users/ktavabi/opt/miniconda3/envs/obiwan/lib/python3.9/typing.py", line 268, in inner
>     return func(*args, **kwds)
>   File "/Users/ktavabi/opt/miniconda3/envs/obiwan/lib/python3.9/typing.py", line 820, in __getitem__
>     params = tuple(_type_check(p, msg) for p in params)
>   File "/Users/ktavabi/opt/miniconda3/envs/obiwan/lib/python3.9/typing.py", line 820, in <genexpr>
>     params = tuple(_type_check(p, msg) for p in params)
>   File "/Users/ktavabi/opt/miniconda3/envs/obiwan/lib/python3.9/typing.py", line 157, in _type_check
>     raise TypeError(f"{msg} Got {arg!r:.100}.")
> TypeError: Parameters to generic types must be types. Got 5.

**Comment by hoechenberger** [comment]
Interesting, I'll have a look!

**Comment by hoechenberger** [comment]
@ktavabi So far I cannot reproduce this… could you please share your config file?

**Comment by ktavabi** [comment]
[Here you are](https://github.com/ktavabi/paros-bids/blob/f3a9e1b03a9df6d169b93b254242413919d8af09/paros_bids_config.py). Thanks.

**Comment by hoechenberger** [comment]
Thank you, I will have a look later today!
