### ISSUE TITLE
ENH/API: script 01 obsolete for EEG

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-bids-pipeline#321]
I am wondering if we can skip script 1; in my use case it simply copies/duplicates the EEG files (which I already duplicated by converting to bids ...). 

cc @hoechenberger @agramfort @sappelhoff

**Comment by agramfort** [comment]
I was thinking the same this we work working with EEG. The first on
maxfilter should not do anything when working with EEG.

>
