### ISSUE TITLE
DOC: tell consistently which params in config matter in which script

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-bids-pipeline#323]
I noticed that comments like  "# done in 02-frequency_filter.py" do not appear consistently in the config. It would be nice to have every script mentioned at least once. WDYT @hoechenberger @agramfort ?

**Comment by hoechenberger** [comment]
Sounds fair, I'll take a look!

**Comment by dengemann** [comment]
I think it would help a lot first-time users. We can look/zoom/pr this together whenever you have time.

**Comment by larsoner** [comment]
To me the layout in https://mne.tools/mne-bids-pipeline/settings/general.html already sets this up pretty well. Is that enough @dengemann, or do you think we need to add these to the actual (default) config file itself?

If we do add them to the config file itself, then in principle the doc sections could be automatically created by the "file annotations" we have added to the config file, reducing redundancy, which is nice. But maybe overkill...

**Comment by dengemann** [comment]
I think the way it's done now is intuitive, good enough!
