### ISSUE TITLE
ENH: config has no option for rejection by flat

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-bids-pipeline#325]
I think it would be important to also pass the flat params to the the epoching script. Any thoughts? @drammock @hoechenberger @agramfort

**Comment by hoechenberger** [comment]
Yes, we could add that. I just didn't feel the need so far because I haven't actually encountered absolutely flat data in the wild in a channel that wasn't marked as "bad" anyway. Is this a thing that actually occurs?

**Comment by dengemann** [comment]
Yes :) otherwise I would not bother. E.g. in general anesthesia you can have burst suppression, which gives flat EEG.

**Comment by agramfort** [comment]
see https://mne.tools/stable/generated/mne.Epochs.html

Rejection parameters based on flatness of signal. Valid keys are 'grad',
'mag', 'eeg', 'eog', 'ecg'. The values are floats that set the minimum
acceptable peak-to-peak amplitude (PTP). If the PTP is smaller than this
threshold, the epoch will be dropped. If None then no rejection is
performed based on flatness of the signal.

it you set flat=dict(grad=1e-14) it will consider it flat if ptp is less
than 1e-14 T/m

>

**Comment by hoechenberger** [comment]
Oh … the heck, what was I reading about then? 🤔 
Anyway, this seems like a trivial fix then!

**Comment by larsoner** [comment]
Closing as dup of #446 because it says what function should be used
