### ISSUE TITLE
Create report just for preprocessing

### ISSUE THREAD

**Issue by guiomar** [mne-tools/mne-bids-pipeline#332]
Hi! I think it could be nice to have the option of creating a report just with the "preprocessing" steps. Currently it seems it looks for the *_ave.fif file, but maybe this is generated in the "sensor" part?

**Comment by agramfort** [comment]
the report needs a lot of love indeed. It is indeed a good idea to split it
by sections (preprocessing, sensor, source)

would you have the bandwidth to help with this?

>

**Comment by guiomar** [comment]
Sure! if you show me some basics, so I can follow the logic and don't mess anything, I can give it a try :)
(I'm just learning all this, so I'll go a bit slowly at the beguining)

**Comment by agramfort** [comment]
can you join the mne discord server https://discord.gg/cQHS5qtV so we can
easily chat?

>

**Comment by guiomar** [comment]
Sure! Thanks!

**Comment by larsoner** [comment]
I think this is more or less taken care of by the section headings in the left bar of the report nowadays so I'll close, but feel free to reopen if it's still not usable
