### ISSUE TITLE
Explicate to which processing steps each config parameter applies, and whether params are optional or required

### ISSUE THREAD

**Issue by guiomar** [mne-tools/mne-bids-pipeline#333]
Hi!

Would you think it would be a good idea to have some information about the specific config parameters needed for each step (preprocessing/sensor/source)?

**Comment by guiomar** [comment]
My apologies if this doesn't make sense. I'm trying to figure out which parameters are strictly necessary for each of the steps

**Comment by guiomar** [comment]
This parameter: "interpolate_bads_grand_average" doesn't show on the website

**Comment by agramfort** [comment]
I would suggest you do a pair programming session with @hoechenberger so
you feel

> comfortable contributing fixes ot the pipeline documentation and code.
That would be very helpful.

**Comment by guiomar** [comment]
That would be fantastic!

**Comment by guiomar** [comment]
I'll try to differentiate for each of the parameters:
1) which steps are they being used in: preprocesing, sensor, source
2) are they REQUIRED, RECOMMENDED or OPTIONAL (similar to what we have in BIDS)

That way we could have a better idea of which parameters we really need to set in the configuration file

**Comment by hoechenberger** [comment]
> 2\. are they REQUIRED, RECOMMENDED or OPTIONAL (similar to what we have in BIDS)

This is a great idea. We should think about how to point this out in the documentation. We might want to create small macros (which you could use by simply typing `{{ required }}` or similar) to add certain markup elements.

**Comment by hoechenberger** [comment]
> RECOMMENDED

I don't think we should have this one, though – seems more opinionated than the pipeline already is **LOL**

**Comment by guiomar** [comment]
Ok! Then we'll go with required and optional :)

**Comment by hoechenberger** [comment]
It was just a thought, I'm totally willing to discuss this :)

@SophieHerbst @agramfort WDYT? Relevant discussion starts here: https://github.com/mne-tools/mne-bids-pipeline/issues/333#issuecomment-848985819

**Comment by guiomar** [comment]
Hi! I have added where each of the settings in the config are used. I have opened a PR so you can see. We can delete it later, when you tell me how this should be done more efficiently. Some parameters are only used in the general.md but nowhere else. Maybe in the future they will and that's why you have them.

With this we could change the website documentation files accordingly.

**Comment by guiomar** [comment]
Hi @hoechenberger this is the branch indicating where each parameter of the config file is used: https://github.com/guiomar/mne-study-template/tree/config-param-steps
How would it be the best way to do it?

**Comment by agramfort** [comment]
@guiomar can you open a PR from this branch so we can more easily see the diff? 🙏

**Comment by hoechenberger** [comment]
I think this has been solved via #866
