### ISSUE TITLE
Warning when 0 EOG-related IC detected ?

### ISSUE THREAD

**Issue by crsegerie** [mne-tools/mne-bids-pipeline#347]
During the preprocessing step of the pipeline, I obtained:

`12:09:41 [Step-04][sub-403] Performing automated EOG artifact detection …`
`12:09:41 [Step-04][sub-403] Detected 0 EOG-related ICs in 18 EOG epochs.`
`12:10:46 [Step-04][sub-403] Saving ICA solution and detected artifacts to disk.`

I think it would be great if a warning appeared saying:

"Warning: zero EOG-related IC was detected, the EOG epochs will not be corrected.
Checking that EOG epochs are not superposed with actual task epochs...
There are 3 superpositions between task epochs and OEG epochs. Marking those 3 task epochs as rejected."

Or maybe it could just say:
"Warning: zero EOG-related IC was detected, this is highly suspicious. A manual check is required." 

What do you think?

**Comment by agramfort** [comment]
+1

PR welcome

>
