### ISSUE TITLE
Ensuring beginners will be able to understand the pipeline

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#350]
A discussion with @crsegerie, @SophieHerbst, and @agramfort (which was later continued between @SophieHerbst and me) highlighted a bunch of issues:

1. By asking users to run the pipeline via `run.py`, they don't "get to see" the individual processing scripts anymore, unless they explicitly start looking for them. So it increases the threshold to understanding what's going on under the hood

    **Proposal:** ???

1. Some scripts have reached a high degree of complexity, and it's sometimes difficult to figure out the "important" bits between all the filename and path wrangling.

    **Proposal:** It could be worthwhile to see if we can split large & complex code blocks into smaller functions?

1. We're applying loads of (carefully-chosen!) default configuration options. This allows users to create minimal config files that only affect the subset of settings they actually **want** and **need** to change. However, the drawback is that this kind of obfuscates which settings are actually being applied in total – users never get to see the final config file that the pipeline is actually running with, as we only create it in memory on execution (by first reading our default `config.py` and then loading the user settings on top of that)

    **Proposal:** Users are already free to specify **all** settings in their own config if they want to. Yet, asking them to **always** do so could be overwhelming, too! And if they simply copy the pipeline's `config.py` and rely on all the defaults without ever actually **looking** at them, we're back to square one… The [mne-bids-pipeline-runner](https://github.com/hoechenberger/mne-bids-pipeline-runner) already offers users to create a config file (currently, this will only create a config of our template `config.py`). This could be extended such that it would ask the user questions -> allow for an interactive creation of the config. So users would be forced to at least explicitly accept the default values.

1. It might be difficult for users to figure out which individual config settings affect which steps of the pipeline. 

    **Proposal:** @guiomar brought this up in #333 and already started working on it. We'll go over all settings again and see if they appear in the correct spots of the documentation. Also I'm thinking of a way to automatically extract from each script which settings it actually uses (by scanning for `config.xxx` access) and automatically add it to the docs. Needs discussion

cc @dengemann

**Comment by larsoner** [comment]
To me the logging with brackets is now quite helpful for this.

What I think would be helpful would be to have a flow diagram of script names + filenames, at least for one example. In principle it seems like this could be autogenerated for each pipeline based on the joblib cache entries. It might be ~100 lines to get this to work, but doing so would make it so that the flow diagram process is automated and we don't ever have to manually update it...
