### ISSUE TITLE
runs = "all" assumes that all participants have the same runs

### ISSUE THREAD

**Issue by crsegerie** [mne-tools/mne-bids-pipeline#352]
The runs = "all" parameter makes the assumption that the runs are identical for each subject. 

(I think the function `get_entity_vals(get_bids_root(), entity_key='run')` in the function `get_runs()` in the config.py file reunites all the run names that exist for all the subjects)

for example, if subject 403 has only 8 runs when subject 512 has 9 runs, we then get errors that look like this when dealing with subject 403:

> 2021-05-27 15:31:01 INFO Successfully finished running: init_derivatives_dir
> 2021-05-27 15:31:01 INFO Now running: import_and_maxfilter
> 15:31:02 [Step-01] Running Step 1: Data import
> 15:31:02 [Step-01][sub-403] Loading reference run: 01.
> 15:31:04 [Step-01][sub-403] Applying Maxwell filter to experimental data.
> 15:31:10 [Step-01][sub-403] Processing empty-room recording …
> 15:31:11 [Step-01][sub-403] Applying Maxwell filter to empty-room recording
> 15:31:14 [Step-01][sub-403] Applying Maxwell filter to experimental data.
> 15:31:24 [Step-01][sub-403] Applying Maxwell filter to experimental data.
> 15:31:33 [Step-01][sub-403] Applying Maxwell filter to experimental data.
> 15:31:44 [Step-01][sub-403] Applying Maxwell filter to experimental data.
> 15:31:53 [Step-01][sub-403] Applying Maxwell filter to experimental data.
> 15:32:02 [Step-01][sub-403] Applying Maxwell filter to experimental data.
> 15:32:13 [Step-01][sub-403] Applying Maxwell filter to experimental data.
> 15:32:21  A critical error occurred.

It would be good to add a warning immediately in the config.py if the participants do not have the same number of runs and do not have the same list of run names. What do you think ?

**Comment by hoechenberger** [comment]
Excellent catch, @crsegerie!!

I'm not sure what a good practice would look like here. In some studies some participants legitimately have more runs than others. We should handle this transparently -- in the end, the report will display this difference.

This question also touches upon the question whether and to what extent the Pipeline should try to "validate" the input BIDS dataset. I would say we keep it to a bare minimum, because this sort of functionality belongs into MNE-BIDS.

So for now, I'd suggest we find a way to retrieve a subject-specific list of runs for each individual participant

**Comment by crsegerie** [comment]
Yeah, exactly: retrieve a subject-specific list of runs for each individual participant, would solve this. We can also quickly notify the user that the different subjects have different runs so that the user keeps this in mind.

**Comment by SophieHerbst** [comment]
I like the idea of notifying the user, but allowing to have different runs per subject. It is not uncommon to loose one run during recording, and we would not want to throw away all the other runs from the participant.

**Comment by hoechenberger** [comment]
@crsegerie 
If you work on this, it's okay to make two separate PRs for the two issues (allowing unequal numbers of runs between participants; warn in that case) if that makes things easier for you. But putting it all in one is okay too, of course
