### ISSUE TITLE
Missing Baseline interval Check 

### ISSUE THREAD

**Issue by crsegerie** [mne-tools/mne-bids-pipeline#356]
I think there is a missing check which should have followed the reading of the config file:

![image](https://user-images.githubusercontent.com/38733898/120214697-1ff2e780-c235-11eb-90fa-bfcb71f401d6.png)

After having set the baseline to (-1, 0), I should have been warned immediately that this won't be compatible with the epochs data.

**Comment by crsegerie** [comment]
Ok, I've been looking at how we can correct this.  At first, it seemed to me that fixing this problem would be quite easy since the `_check_baseline` function is a utility function that already exists in mne-python: it would be enough to add a check just after the declaration of the config file, and not just wait until the last moment. 

But we would need to use the `_read_evoked` function (because read_evoked returns among other things `times` and `info[sfreq]` which are necessary arguments of `_check_baseline`), i.e. we would read all the data by looping over the subjects. I don't know if this is desirable. What do you think?

Also, to be consistent this would mean that all the other checks of the other parameters of the config file would have to be done right after the configuration file, which is not possible.

**Comment by agramfort** [comment]
you can make it simple just do

evoked = epochs.average()
# check baseline here
evoked = evoked.apply_baseline(baseline)

>

**Comment by hoechenberger** [comment]
Wait wait wait, am I missing something here? To me it seems we could do an extremely simple check within `config.py`, something like:

```python
if config.epochs_tmin < config.baseline[0] or config.epochs_tmax > config.baseline[1]:
    raise
```

Or am I missing something here?
