### ISSUE TITLE
config.crop and multiple runs

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#357]
Current docs seem to indicate the `crop` setting applies to the concatenated data an entire session:

```
crop: Optional[Tuple[float, float]] = None
"""
Crop the raw data to the specified time interval ``[tmin, tmax]`` in seconds.
If ``None``, do not crop the data.
"""
```

However, we're actually cropping each run individually.

Either we
- keep the current behavior, but rename the setting to `crop_runs` or something similar,
- only apply cropping on concatenated data (i.e., after concatenating all runs) -> can be problematic in some cases if runs are long and we need to crop due to memory constraints!
- keep the current behavior but introduce an additional setting for cropping the concatenated data

WDYT?

**Comment by agramfort** [comment]
+1 to crop all runs as it is

and yes let's rename to crop_runs to be more explicit

>
