### ISSUE TITLE
Overlapping titles in ECG Scores

### ISSUE THREAD

**Issue by crsegerie** [mne-tools/mne-bids-pipeline#364]
In my sub-197_task-tiwm_proc-ica+components_report.html, the figure showing the ECG scores of the different CIs, the titles are superimposed. There is no such bug in the figure just below showing the EOG scores.

See the faulty ECG-scores figure:

![image](https://user-images.githubusercontent.com/38733898/120515899-1604ec00-c3cf-11eb-92bf-531760449559.png)

Whereas there is no bug for EOG-scores:

![image](https://user-images.githubusercontent.com/38733898/120516401-9c213280-c3cf-11eb-8036-a9bb383a3169.png)

**Comment by hoechenberger** [comment]
Can you check whether we (that is, MNE-Python in this case) use `tight_layout` for EOG, but not for ECG?

**Comment by crsegerie** [comment]
I'm pretty sure the tight_layout in the function plot_ica_scores is already applied for both EOG and ECG.

![image](https://user-images.githubusercontent.com/38733898/121025758-cbf08180-c7a5-11eb-9db2-fb1ca0b0703f.png)

**Comment by hoechenberger** [comment]
I'm not sure what `tight_layout` does here specifically (would need to look at the MNE implementation), but at least Matplotlib's `fig.tight_layout()` doesn't take into account the suptitle and one needs to specify a bounding box a la `fig.tight_layout(rect=[0, 0.03, 1, 0.95])`

**Comment by crsegerie** [comment]
Yes you are right. I just looked at the tight_layout in the utils of mne-python, and it seems there are some underlying complexities...

**Comment by hoechenberger** [comment]
This has been resolved upstream in https://github.com/mne-tools/mne-python/pull/9489
