### ISSUE TITLE
Allow for make_epochs as entry point when using EEG data

### ISSUE THREAD

**Issue by dengemann** [mne-tools/mne-bids-pipeline#400]
title says it all @hoechenberger

**Comment by agramfort** [comment]
I say it’s not top priority 

It’s not so trivial. 

@dengemann give it a shot if it’s a blocker for you

**Comment by dengemann** [comment]
well let's keep it open, I will work around

**Comment by hoechenberger** [comment]
> It’s not so trivial.

I second this.

**Comment by larsoner** [comment]
I doing `l_freq = h_freq = None` it gets to epoching quickly since it's essentially just a `copyfile` at that point, so I think we can consider this "good enough" to close

**Comment by dengemann** [comment]
Yes, sounds good!
