### ISSUE TITLE
Generate head surfaces in our FreeSurfer step to save time when we're later running the pipeline

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#420]
Currently we generate the surfaces during the BEM step if they don't exist; but it would make sense to already produce them as part of the FS step. Also will make it easier to run coreg before running the pipeline.

**Comment by agramfort** [comment]
Why not but I would allow to compute the bem surfaces for already available recons. So it would be 2 scripts in the anatomy batch of steps

**Comment by hoechenberger** [comment]
Oh I was only referring to `mne.bem.make_scalp_surfaces()` here, which we currently run in `01-make_bem_surfaces.py` if the surfaces cannot be found.

**Comment by agramfort** [comment]
yes but it's still something you may want to do from an existing freesurfer
recon.

>

**Comment by hoechenberger** [comment]
> yes but it's still something you may want to do from an existing freesurfer recon.

Yes, this is already implemented in `main`! We simply do it "on demand" during the source processing steps. Are you suggesting that we should have a second anatomy script that does this (and only this)? Might be a bit overkill but I can have a look
