### ISSUE TITLE
CI: CircleCI builds causing backups

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-bids-pipeline#434]
In MNE the `main` build is slow (~2h) but on PRs it's fast (~15 min) because we triage what needs to be built based on changes. It would be good if there were some way to do the same thing for MNE-BIDS-Pipeline, as the PRs currently open are causing backups for all `mne-tools` projects on CircleCI.

One easy and useful option would be to only build one project on a given PR unless the `[circle full]` tag is passed, but always do the full build on `main` builds. I'm happy to open a PR to do this if people agree it would be helpful.

**Comment by agramfort** [comment]
I like this idea.

I agree that we are clogging the system....

PR welcome

>

**Comment by larsoner** [comment]
Also I just did:
```
$ git fetch upstream
remote: Enumerating objects: 865, done.
remote: Counting objects: 100% (253/253), done.
remote: Compressing objects: 100% (28/28), done.
remote: Total 865 (delta 225), reused 234 (delta 222), pack-reused 612
Receiving objects: 100% (865/865), 455.71 MiB | 30.27 MiB/s, done.
```
My last fetch was about 2 months ago, and this one fetched 500 MB of data. It might be worth squashing the `gh-pages` branch at some point, or maybe just uploading directly to `mne-tools.github.io`...

**Comment by hoechenberger** [comment]
> It might be worth squashing the `gh-pages` branch at some point

We're actually overwriting it entirely with each merge to `main` (it's the `no-history` flag here):
https://github.com/mne-tools/mne-bids-pipeline/blob/f8b987d94d11f1677d06144b9982bd67084009f6/.circleci/config.yml#L738

**Comment by larsoner** [comment]
Oh actually that means the entire website will get fetched anytime it changes (won't even have a base commit to diff off of in case only a few files change)...

Then maybe the solution is to write to `mne-tools.github.io` directly instead.

**Comment by agramfort** [comment]
>
> Oh actually that means the entire website will get fetched anytime it
> changes (won't even have a base commit to diff off of in case only a few
> files change)...
>
> Then maybe the solution is to write to mne-tools.github.io directly
> instead
>

can we do like we do for mne-tools.github.io ? we commit a diff? that's
what you suggest @larsoner?
