### ISSUE TITLE
Group studies

### ISSUE THREAD

**Issue by ktavabi** [mne-tools/mne-bids-pipeline#494]
Hi everyone,
Is there any consensus on handling `group` in a BIDS-compliant fashion? I am asking because at present the pipeline doesn't appear to be geared toward a user-friendly `split-apply-combine` approach for secondary analysis. I have a decent-sized dataset that I am more than happy to share as an _open_ use case.

cc @larsoner

**Comment by hoechenberger** [comment]
Hello @ktavabi, could you specify in more detail what it exactly it is you want to do? What we already have is some rough support for averaging individual results (producing a `sub-average` pseudo-subject). I think we could add more stats and do inference on a group level quite easily, at least up to a certain extent…

**Comment by ktavabi** [comment]
> I think we could add more stats and do inference on a group level quite easily, at least up to a certain extent…
Hi, @hoechenberger I believe we're already doing a decent job of group-level inferential with the decoder. 

My issue is two-fold (i) is there a BIDS specification for `group`, if not then that is an outside scope problem. (ii) I have an independent two-sample design that I would like to simply split on `group` before producing `sub-average`. E.g., a `sub-group-average` pseudo-subject from the `subjects` list in my configuration file. Does that make sense?

**Comment by hoechenberger** [comment]
Hello @ktavabi, I'm currently a bit busy but I hope I'll be able to get back to you sometime tomorrow (UTC)

Best wishes

**Comment by ktavabi** [comment]
NP I am on vacay thru mid-January.

**Comment by hoechenberger** [comment]
Shouldn't we keep this open, @ktavabi? Or have you found a good solution?

**Comment by ktavabi** [comment]
Hey man, I appreciate the gesture. At this point, I am just trying to finish up, so just falling back onto solutions from yesteryears. 

Feel free to open a new issue. IMO It would be nice / very useful to integrate some of mne-R into the secondary analysis here, I am sure @dengemann has some elegant solutions for this.
