### ISSUE TITLE
Rename config.decim to epochs_decim

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#501]
The `decim` setting in `config.py` only applies to epoching (as the docstring correctly states). To make things more obvious and consistent, I propose to rename it to `epochs_decim`. Likewise, `ica_decim` should become `ica_epochs_decim`.

Thoughts?

**Comment by larsoner** [comment]
Probably should have done this for 1.0 if we were going to do it :grimacing:

I'll mark for 2.0 I guess?

**Comment by hoechenberger** [comment]
😅😅😅

**Comment by hoechenberger** [comment]
Ok let me try to be more constructive:

Let's do this change and a new release quickly, I will hold off announcing the pipeline until then. Gives me more time to prepare a public announcement. Let's schedule this for sometime this week, ok?

cc @larsoner
