### ISSUE TITLE
Run script broken

### ISSUE THREAD

**Issue by ktavabi** [mne-tools/mne-bids-pipeline#512]
`run.py` exits with SyntaxErrors...

> File "/Users/ktavabi/Github/mne-study-template/run.py", line 43
>    logger.info(f'Now running: {script}')

Also, why not [Black](https://pypi.org/project/black/)?
@agramfort 

<img width="831" alt="image" src="https://user-images.githubusercontent.com/4381290/151645159-1eb2d063-d88b-40f7-b8b3-860e5e69ccdf.png">

**Comment by hoechenberger** [comment]
Hello, I'm a little confused by the error you're seeing here – is that a very old version of the pipeline? Because line 43 doesn't look like that anymore 😅

Black might be a good idea, sure, we could give it a shot! I would need to play with it a bit first. Generally I like its opinionated approach.

**Comment by ktavabi** [comment]
> Hello, I'm a little confused by the error you're seeing here – is that a very old version of the pipeline? Because line 43 doesn't look like that anymore 😅
😭 I am done with IDEs and their $PATH environments.  

> Black might be a good idea, sure, we could give it a shot! I would need to play with it a bit first. Generally, I like its opinionated approach.
`Black` would be a major overhaul for you guys. But it would be a desirable long-term solution, the mne-template codebase may be a good place to start, then mne-bids, and finally the mothership,mne.

**Comment by hoechenberger** [comment]
> 😭 I am done with IDEs and their $PATH environments. Just a thought, but if we bury the 'MASTER' branches, it would undoubtedly help us politically incorrect dinosaurs from making these types of errors. Even Grammarly complains about the word 😑
> 

Oh, so you were still pulling from the old branch, which doesn't exist anymore? I thought GitHub would redirect things automatically … bummer!



> `Black` would be a significant overhaul for you guys. But it would be a desirable long-term solution; the mne-template codebase may be an excellent place to start, then mne-bids, and finally the mothership,mne.

I can see us switching to Black for the Pipeline and maybe MNE-BIDS; but MNE-Python, no way, we'd have to touch too many lines of code and this would "spoil" the git history, so I don't think we'd find an agreement among devs to do this.

**Comment by ktavabi** [comment]
Bummer indeed. No one told the IDE's about the rebrandings 👍
