### ISSUE TITLE
RuntimeError: dig cannot be set directly. Please use method inst.set_montage() instead.

### ISSUE THREAD

**Issue by ktavabi** [mne-tools/mne-bids-pipeline#513]
🤷🏽 

> Traceback (most recent call last):
>   File "/Users/ktavabi/Github/mne-study-template/config.py", line 1538, in wrapper
>     return func(*args, **kwargs)
>   File "/Users/ktavabi/Github/mne-study-template/scripts/preprocessing/01-import_and_maxfilter.py", line 451, in main
>     parallel(run_func(subject, session) for subject, session in
>   File "/Users/ktavabi/Github/mne-study-template/scripts/preprocessing/01-import_and_maxfilter.py", line 451, in <genexpr>
>     parallel(run_func(subject, session) for subject, session in
>   File "/Users/ktavabi/Github/mne-study-template/scripts/preprocessing/01-import_and_maxfilter.py", line 410, in run_maxwell_filter
>     raw_er.info['dig'] = dig
>   File "/Users/ktavabi/Github/mne-python/mne/io/meas_info.py", line 761, in __setitem__
>     raise RuntimeError(self._attributes[key])
> RuntimeError: dig cannot be set directly. Please use method inst.set_montage() instead.
> > /Users/ktavabi/Github/mne-python/mne/io/meas_info.py(761)__setitem__()
> -> raise RuntimeError(self._attributes[key])

**Comment by hoechenberger** [comment]
Ah yes, this is one of our hacks …

@agramfort Do you know from the top of your head whether it's safe to simply switch to using `set_montage()`? (I haven't looked at the code of this method yet)

**Comment by hoechenberger** [comment]
I think we should try simply `_unlock()` info, this should allow us to set the `dig` property

**Comment by larsoner** [comment]
Agreed

**Comment by agramfort** [comment]
+1

**Comment by ktavabi** [comment]
Anything I can do/provide to speed this along?

**Comment by hoechenberger** [comment]
Yes, poke me so I don't forget about it 😅 It should be a trivial fix which I'll try to to today. If this isn't fixed by Wednesday, please post here again, I probably simply forgot....

**Comment by ktavabi** [comment]
Np. You have till my Wed., 🌴 or European Thursdays to get it done.

**Comment by hoechenberger** [comment]
@ktavabi I appears you're still using some old version of our code here! This problem doesn't exist in `main`.

I'd suggest you do a fresh checkout. The main issue seems to be that at one point, we renamed the Study Template to the BIDS Pipeline, and that may explain why you're still stuck with outdated code.

**Comment by ktavabi** [comment]
Okay. This is a fresh `conda` environment with reinstalls of mne-python, mne-bids, and a recently checked-out pipeline repo.  Maybe the first thing a pipeline/heuristic should do is check to see the environment is valid? It's a bit useless to get an RTE like this with only 50% of my dataset, basically, if I didn't have ERM data the pipeline would proceed without error, and I'd have no idea I am using the wrong codebase 🤷🏽  Es no Bueno! I'll try again.

**Comment by ktavabi** [comment]
1. I know in EXPYFUN there is a commit hash check-switch, so that's a possibility, to exit if the template commit hash is too old
2. My only comment on the guide is that the aesthetics drift afar from the styles in mne-python, mne-bids, otherwise I've just been bulldozing through.
3. No. When I deploy my `env.yml` with `pooch` a stable version of MNE is installed. I am about 99.95% sure `pooch` is the culprit

**Comment by hoechenberger** [comment]
> 1. I know in EXPYFUN there is a commit hash check-switch, so that's a possibility, to exit if the template commit hash is too old

Ah, so you'd like to have some kind of check that tells you, "whoops, seems you're out of date! wanna update?", did I get this right?

> 3. No. When I deploy my `env.yml` with `pooch` a stable version of MNE is installed. I am about 99.95% sure `pooch` is the culprit

Can you share your `env.yml` so I can take a look?

**Comment by ktavabi** [comment]
> Ah, so you'd like to have some kind of check that tells you, "whoops, seems you're out of date! wanna update?", did I get this right?

Right! if you like you could even specifically message it to me personally "whoops, you dumbass! you're using spoiled milk..." 😂


[obiwan.txt](https://github.com/mne-tools/mne-bids-pipeline/files/7980772/obiwan.txt)

**Comment by ktavabi** [comment]
Thanks for your help @hoechenberger today. I am now up & running with a fresh update of the pipeline code. Not sure how much of this thread is still valid, but I will leave it to you to reopen a new issue with additional features, if any. 

WRT to the `conda` environment, I will abandon Conda and use system python going forward.
