### ISSUE TITLE
3D figures are missing from rendered docs

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#522]
https://mne.tools/mne-bids-pipeline/examples/ds000248/sub-01_task-audiovisual_report.html

sensor alignment and stc plots are just black squares

**Comment by larsoner** [comment]
You can try disabling all the fancy MNE_3D_OPTION_* options in `circle.yml`

If that doesn't work, try downgrading to Ubuntu 18.04 (if you're not using it there). The Mesa there has worked better for MNE-Python doc builds at least. But even on 20.04 it would render, it was just the opacity of surfaces that was messed up...
