### ISSUE TITLE
It should be easier to see at a single glance how many epochs have been rejected, both on individual and on group/study level

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#524]
Necessary for when we don't know which rejection thresholds to use yet.

**Comment by larsoner** [comment]
The epochs reports have drop logs now so I think we can close this

https://mne.tools/mne-bids-pipeline/examples/ds000248/sub-01_task-audiovisual_report.html#global-84

But feel free to reopen if it's not enough
