### ISSUE TITLE
Running functions on google colab ipynb server?

### ISSUE THREAD

**Issue by anthonyromyn** [mne-tools/mne-bids-pipeline#525]
Hey MNE team,

I've run into a bit of a snag trying to use the pipeline on a ipynb google colab server. I have data on a google drive, the google drive is mounted to the colab server. Using Run.py, mne/utils/check.py is failing to find the data in a bit of a puzzling way. I've documented with 4 pictures below.

1. I try to run Run.py and it throws these errors. It can't find the sub-cbm00156 folder
![Screenshot from 2022-03-29 18-14-23](https://user-images.githubusercontent.com/37704753/160717164-e33328cb-4a92-4543-be2f-9fd2beeb1d64.png)

2. sub-CBM00156 exists, so of course it's the caps cbm/CBM? 
![Screenshot from 2022-03-29 18-14-42](https://user-images.githubusercontent.com/37704753/160717204-285069f0-9319-4fa0-8c69-ed69d4176115.png)

3. I rename sub-CBM00156 -> sub-cbm00156 and now it wants sub-CBM00156
![Screenshot from 2022-03-29 18-15-54](https://user-images.githubusercontent.com/37704753/160717211-e310b49b-ae2b-4c5d-8a47-45ed6b0142e3.png)

4. And this is just a photo of proof that I did indeed rename sub-CBM00156 -> sub-cbm00156
![Screenshot from 2022-03-29 18-29-47](https://user-images.githubusercontent.com/37704753/160717448-cedddc0b-d1a5-49fb-b770-fa417dc0f906.png)

Anyone know why this is happening or what to do about it?
Thanks for your time!
Anthony

**Comment by hoechenberger** [comment]
Hello @anthonyromyn!

> 1. I try to run Run.py and it throws these errors. It can't find the sub-cbm00156 folder

Could you please share `config_chbp_eeg.py`? I believe there might be an issue with how you specify the BIDS root directory.

Best wishes,

    Richard

**Comment by anthonyromyn** [comment]
Hey Richard,

For sure, thanks!

[config_chbp_eeg.zip](https://github.com/mne-tools/mne-bids-pipeline/files/8382341/config_chbp_eeg.zip)

**Comment by hoechenberger** [comment]
@anthonyromyn looking at the screenshots again, there's multiple files and folders both with uppercase and lowercase spelling. Could you just clean that up such that **only** one or the other exists? You'd also need to check the contents of `*_scans.tsv` to point to the correct files.
