### ISSUE TITLE
Proposal to allow more complex contrasts

### ISSUE THREAD

**Issue by mathias-sm** [mne-tools/mne-bids-pipeline#536]
For my use case, direct contrasts `cond_A - cond_B` are not the most informative.

I was wondering whether we could implement more complex contrasts, e.g. `-.5*cond_1 -.5*cond_2 + cond_3` or similar? `nilearn` does this with [expression_to_contrast_vector](https://github.com/nilearn/nilearn/blob/d43e4ff0e150634c474f834d523ada1529d218d1/nilearn/glm/contrasts.py#L21) by leveraging [pandas.DataFrame.eval](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.eval.html#pandas-dataframe-eval), see [the relevant line here](https://github.com/nilearn/nilearn/blob/d43e4ff0e150634c474f834d523ada1529d218d1/nilearn/glm/contrasts.py#L43)

I understand that it would make safe-naming contrasts tedious, so maybe much like [conditions](https://github.com/mne-tools/mne-bids-pipeline/blob/c40a9f044f33394a6dd73b83f79616cb1d427e80/config.py#L839) we should allow (force?) `contrasts` to be of type `Dict[str, str]`, the first `str` being a name and the second an expression to evaluate at runtime (I don't think we could enforce anything better with the type system available). Then in `config.py` one could write:

```python
contrasts = {"main_effect": "-.5*cond_1 - .5*cond_2 + cond_3",
             "gradient": [...],
             "simple": "cond_1 - cond_2"}
```

I wouldn't mind working on a pull request to do this, with some early input to make sure this is relevant to the maintainers, in particular I think it's worth considering the following:
* This may change some types in `config.py` so potentially break things
* What would be relevant tests for this?

**Comment by agramfort** [comment]
I love the idea but I am not sure about the API. If would prefer to keep
contrast a list
and allow to have certain entries be strings that will be interpreted to be
passed to
some df.eval function. You would then ignore the contrasts which are
strings in the
decoding. WDYT?

**Comment by mathias-sm** [comment]
Thanks for the feedback! I hadn't realized that decoding would make the first proposal a no-go.
Then `contrasts` could have type `Iterable[Union[Tuple[str, str], Tuple[str, str]]]`, where the `Tuple` is either a pair of conditions to contrast or a `name`/`formula` pair. Maybe the `python` type system can express this distinction better? Not sure. And then at runtime we see if a contrast is of one type or the other, and either keep the current code or use df.eval.
Also, thinking about it, the implementation using `df.eval` might rather be implemented in `combine_evoked`, in `mne`?

**Comment by hoechenberger** [comment]
I'd propose a more elaborated, but also more explicit API, that would allow for the following:

```python
contrasts = [
    {
        'name': 'contr_A_vs_B',
        'conditions': ['A', 'B'],
        'weights': [1, -1]
    },
    {
        'name': 'contr_A_vs_B_vs_C',
        'conditions': ['A', 'B', 'C'],
        'weights': [0.7, -1, 0.3]
    }
]
```    
Here it's very clear what to do, no magic required, and it's easy to write.

**Comment by agramfort** [comment]
I like that too

**Comment by mathias-sm** [comment]
Yes, that makes a lot of sense as well. Just looking at the tests included in the `nilearn` codebase, it looks like `df.eval` allows for more convoluted things, [see the tests](https://github.com/nilearn/nilearn/blob/e6591d8907ceae55eea6f04ce181acb6a12743b5/nilearn/glm/tests/test_contrasts.py#L15-L27). I'm not sure why someone would use `face / 10 + (window - face) * 2 - house` and I prefer the more explicit proposition.
With that said: since those aren't meaningful for decoding, maybe we should formally separate the two concepts?

**Comment by agramfort** [comment]
that's possible yes but I fear it's going to make code more complicated
even for basic usage. I would
prefer if one contrast (ie one entry in contrasts) can rename a tuple with
2 entries to be then used
for decoding with a classifier.

**Comment by hoechenberger** [comment]
@agramfort Do you mean something like that?

```
contrasts = [
    {
        'name': 'contr_A_vs_B_vs_C',
        'conditions': ['A', 'B', 'C'],
        'weights': [0.7, -1, 0.3],
    },  # only evoked contrast
    ('A', 'B')  # evoked contrast & MVPA
]
```

**Comment by agramfort** [comment]
yes something like this

**Comment by hoechenberger** [comment]
Proposal:
```python
contrasts = [
    ('A', 'B')  # evoked contrast & MVPA
]
```

should be equivalent to this (and maybe be internally translated to):
```python
contrasts = [
    {
        'name': 'A_vs_B',  # or whatever our default naming is; should also accept None
        'conditions': ['A', 'B'],
        'weights': [1, -1],
    }  # evoked contrast & MVPA, as there are only 2 conditions
]
```

**Comment by mathias-sm** [comment]
So, to make it backward-compatible, we keep previous `Tuples` as valid contrasts, internally convert them (that would be in `config.py`, right?), also accept the `Dict`s from above, and then:
* When decoding, the code would only consider items for which the `len(conditions) == 2` (and the weights to sum to approx. 0?)
* For evoked contrasts, just forward the conditions and weights to `combine_evoked` and store them with the appropriate name

Seems right? I can work with that.

**Comment by hoechenberger** [comment]
Yes this sounds excellent, @mathias-sm 
The code is sometimes a bit convoluted, so please don't hesitate to share your changes early and ask is anything seems unclear, so we can give feedback
