### ISSUE TITLE
use pytest for tests

### ISSUE THREAD

**Issue by jasmainak** [mne-tools/mne-bids-pipeline#55]
As we discussed [here](https://github.com/mne-tools/mne-study-template/pull/53#issuecomment-524610386), we should pytest.parametrize and as much of the pytest infrastructure as possible rather than reinventing the wheel.

**Comment by larsoner** [comment]
We are doing this for tests that are pytest-able now

**Comment by larsoner** [comment]
Actually thinking about this more, given the latest refactorings, I think we could accomplish this fairly easily now. It would have the (big!) advantage that we could get proper coverage and `codecov` working, too. So I'll reopen this and tackle it in the next few days hopefully
