### ISSUE TITLE
Lowpass filter at 40Hz is hardcoded in the config.py file

### ISSUE THREAD

**Issue by apmellot** [mne-tools/mne-bids-pipeline#556]
In the preprocessing, during the first script (`maxfilter`), raw data is imported with the function `import_experimental_data`. But in this function, there is another function called `_find_bad_channels` in which the raw data is filtered with a lowpass at 40Hz. If I choose a higher h_freq in the config it is not taken into account.

Here is the link to this specific line:
https://github.com/mne-tools/mne-bids-pipeline/blob/main/config.py#L3168

**Comment by hoechenberger** [comment]
OUCH! Good catch!! This should operate on a **copy** of `raw` instead of on the original! Do you want to make a PR?
