### ISSUE TITLE
In _proc-ica_report.html, the captions of the ICA properties plots are incorrect

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#573]
The properties plots are created for all rejected components, i.e., the displayed components can be in basically arbitrary order.

But the captions we display seem to belong to the components with indices `range(len(rejected_components))`.

Could be a problem that needs fixing upstream.

<img width="837" alt="Screen Shot 2022-07-11 at 11 16 08" src="https://user-images.githubusercontent.com/2046265/178231676-e9ec6591-fb9e-4d19-9340-df304f399694.png">

**Comment by hoechenberger** [comment]
I just encountered this error again (or, rather, still).

![Uploading Screenshot 2023-10-28 at 13.26.50.png…]()

**Comment by larsoner** [comment]
I think ICA component 0 gets the channel name `ICA001`. Do you see other mismatches like `ICA component 10` that gets displayed with `ICA002` for example? Or is it always off-by-one (which would perhaps be correct/intended)?

**Comment by hoechenberger** [comment]
It's not off by one, I think we're enumerating the list of rejected ICs and displaying that index (e.g., 0, 1 if we have two rejected ICs), instead of the actual index of the bad ICs (e.g., 1, 5)
