### ISSUE TITLE
DOC: CSS is messed up on some entries

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-bids-pipeline#575]
For me this https://mne.tools/mne-bids-pipeline/features/steps.html looks like

![Screenshot from 2022-07-28 19-08-48](https://user-images.githubusercontent.com/2365790/181652012-26a3aad8-7973-4053-9acf-888a5c9c16f3.png)

**Comment by drammock** [comment]
line-height is set to 0.5 in `docs/source/css/extra.css`. Remove and it will fix it.

**Comment by larsoner** [comment]
Makes sense, need to figure out why it was added in the first place, though, and then decide to live with removing it or find a way to fix whatever problem that was designed to solve...
