### ISSUE TITLE
Making MNE-BIDS-Pipeline a proper Python package

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#580]
It was a conscious design decision **not** to make the pipeline a Python package for the following reasons:

- The code shouldn't be "hidden" from the users, to facilitate looking at and potentially editing the scripts
- It should be possible to have multiple versions of the pipeline installed within the same Python environment, to make working on multiple projects in parallel easier

I believe it's safe to assume that:
- At least since we added support for parallelization and now caching, the complexity of our scripts has exploded and they're not trivial to understand to many users anymore. This is regrettable but apparently unavoidable if we want to have the features that are required to improve pipeline adoption.
- Even before complexity increased to the current level, contributions from folks outside of the "@agramfort bubble" were only marginal.
- It's trivially simple and IMHO good practice to create separate virtual Python environments for every project and analysis you're working on.
- Installation and updating of the pipeline is currently all but user-friendly and I believe a **major** blocker for pipeline adoption.
- The manual steps required to create a custom config file are painful and not well-documented or not documented at all, causing users to do "wrong" things like copying config.py and forgetting to remove all the clutter below that "custom config ends here" horizon, which leads to an infinite recursion when starting the pipeline. 

I had started working on the MNE-BIDS-Pipeline-Runner a while back, attempting to ease this pain; but I never had enough time to bring this project to a usable state:

https://github.com/hoechenberger/mne-bids-pipeline-runner

Ultimately, it was just a workaround for the fact that the pipeline was never available as a package. But I like the idea of providing an interactive prompt that just asks you what to do. 

But with all of the above being said -- I believe it's finally time to:

- Make the pipeline a proper Python package
- Add an entry point to run the pipeline from the command line
- Add an entry point to create a custom / template config. 
- Expose the functionality from `run.py::process()` nicely such that users can invoke the pipeline from their scripts. This bit invaluable to me when it comes to debugging. In fact, every time I wish to debug the pipeline, I create an `mwe.py` inside the pipeline directory, which imports `process` from `run.py`. Only that way can I use the VS Code debugger that I'm used to work with. 

A package could also be installed in "editable" mode, so interested parties could still dump the repository folder wherever they want on their hard drive and edit / look at the code at will. 

I'd like to hear your opinions on the thoughts and proposals above 👍

**Comment by jasmainak** [comment]
This seems to approach the functionality of nipype and ... to some extent neuropycon. I hope we're not re-inventing the wheel here? This idea has been tried before and probably never flew -> the reason I think is that neuroimaging pipelines for bleeding edge MEG research are hard to put in a box. I struggle even with the flexibility of MNE-Python

IMO ... if you can create BIDS-apps for specific well-defined steps of the pipeline, that is a bigger win. A BIDS-app for maxfilter? If I have 300 subjects in BIDS format on AWS, can I point to that directory and get maxfiltered output files in a few minutes?

**Comment by hoechenberger** [comment]
I'm failing to see how this contradicts making it a package? You can put it into a Docker container and that's basically it. In fact, you can do that today already ... making it a package with proper entry points actually will make it easier to have things installed & run through Docker.

But maybe I just don't understand your point 🤔 Could you elaborate how making the pipeline a package would "hinder" the idea of a BIDS app?

Re 300 subjects with MaxFilter -- we've processed some 650 using the MNE-BIDS-Pipeline several times already (Cam-CAN) -- flawless approach utilizing all 80-something CPU cores of our system.

**Comment by jasmainak** [comment]
I guess the goal of making a package relates to what the goals of MNE-BIDS-pipeline are ... when we first released the code, it was to give the community clear guidelines and easy example code to run MEG analysis. If you make it a package, the goal shifts towards giving the community "lego blocks" from which to construct more complex pipelines. You will need to cache intermediate results and handle errors gracefully. I am guessing you would need to create an API ... and that begins to approach the functionality of the above-mentioned packages. 

Could you point me to the Cam-CAN BIDS app? Could I use it today to run 10 BIDS-formatted subjects on my workstation? I do not have sudo privileges ...

**Comment by jasmainak** [comment]
> The manual steps required to create a custom config file are painful and not well-documented or not documented at all, causing users to do "wrong" things like copying config.py and forgetting to remove all the clutter below that "custom config ends here" horizon, which leads to an infinite recursion when starting the pipeline.

Create a thin GUI that allows users to set `config.py` so they never touch code?

**Comment by hoechenberger** [comment]
> I guess the goal of making a package relates to what the goals of MNE-BIDS-pipeline are ... when we first released the code, it was to give the community clear guidelines and easy example code to run MEG analysis. If you make it a package, the goal shifts towards giving the community "lego blocks" from which to construct more complex pipelines.

I don't get that point. All I'm saying is take what we have here and make it into a package so it's easier to install and use.

The code is already so complex that "ordinary" users will struggle to understand what's going on.

> You will need to cache intermediate results and handle errors gracefully. 

Caching has just been added in #563 

> Could you point me to the Cam-CAN BIDS app? Could I use it today to run 10 BIDS-formatted subjects on my workstation? 

There is no BIDS app, it's a config file to be used with the pipeline that @agramfort used a few times to process Cam-CAN. He hosts a repository of such configs, but I've forgotten the URL.

> I do not have sudo privileges ...

I don't see why you should need any?


> Create a thin GUI that allows users to set `config.py` so they never touch code?

Creation of a wizard for config generation was one of the points on my todo list of [MNE-BID-Pipeline-Runner](https://github.com/hoechenberger/mne-bids-pipeline-runner), but I never had enough time to implement this bit.

Still doesn't solve the issue of installation, which would be greatly simplified if we had a package.

**Comment by larsoner** [comment]
To me MNE-BIDS-Pipeline is already very close to a package, and there are more advantages than drawbacks to converting it to one. So +1 for the top-comment plan from me

**Comment by hoechenberger** [comment]
Let's discuss this Friday if we find some time? (I cannot promise anything though)

**Comment by agramfort** [comment]
honestly we should discuss this again.

Let's first start by doing a better documentation about config extensions

**Comment by larsoner** [comment]
Just to add a bit here, I think making this a package could greatly facilitate adoption. We can package it with the MNE installers and tell people they can `mne_bids_pipeline my_config.py` and if everything is setup correctly end up with fully preprocessed data with reporting, caching, etc. I think this should be a goal for the next ~3 months / for the 1.3 release
