### ISSUE TITLE
Implenting CSD in the pipeline

### ISSUE THREAD

**Issue by JeshuaT** [mne-tools/mne-bids-pipeline#586]
Hi! I'm currently looking at how to make my code more reproducible, and the MNE-BIDS-pipeline could be of real value here. I wonder though if it is already possible to do a current source density transformation (see [here](https://mne.tools/stable/auto_examples/preprocessing/eeg_csd.html?highlight=current+source+density)) on the data. I'm interested in localized response effects over the motor cortices, hence the question.

**Comment by agramfort** [comment]
how would you expose this option? save clean evoked also in CSD? just for
the report?

**Comment by hoechenberger** [comment]
Closing for now. Happy to re-open of this feature request pops up again in the future.
