### ISSUE TITLE
DOC: Not all params documented

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-bids-pipeline#590]
Looking at https://mne.tools/mne-bids-pipeline/settings/source/inverse.html I was surprised there was no `loose` param. But then:
```
$ git grep loose
config.py:# loose: Union[float, Literal['auto']] = 0.2
```
We should have some CI process whereby these are checked. I suggest:

1. Write a little `pytest` test for this
2. Put it in `tests/test_doc.py`
3. Add a GH actions run that runs `pytest tests`
4. Add `__test__ = False` to the top of `tests/run_test.py` (and whatever else we [need](https://stackoverflow.com/questions/50610557/how-to-mark-one-function-not-a-test-for-pytest)) so that `pytest` does not try to collect/run it

I can do this if people are on board

**Comment by hoechenberger** [comment]
+1

**Comment by agramfort** [comment]
+1

**Comment by larsoner** [comment]
... wait a minute -- `loose` and `depth` are actually *not* parameters because they were commented out 1.5 years ago in https://github.com/mne-tools/mne-bids-pipeline/pull/220 . Was this intentional? I don't see discussion of it in the PR so it seems like it might have been testing cruft.

**Comment by hoechenberger** [comment]
Could have been intentional, I remember thinking about getting rid of those  parameters as we never used them during any of our analyses. But if you need them now it's good to have them back, I suppose :)
