### ISSUE TITLE
Define a Dockerfile

### ISSUE THREAD

**Issue by abcsds** [mne-tools/mne-bids-pipeline#591]
Idea as follows:

- [x] Choose a a small linux docker image (chose python3.9)
- [.] Install mne via official installation medium (installed directly from pip instead)
- [x] Install missing requirements for mn-bids-pipeline, if any (installed)
- [x] Mount the `bids_root` and work folder as volumes. (mounting is done on running, but volumes are declared)
- [x] Load `config.py`. Maybe through loading a workspace volume? (missing)
- [x] Iun command: `python run.py --config=./work/config.py`(missing)

The black box model would suppose the config.py and the data volume as entry points. The output is writen to the `bids_root` mounted volume.

Here's an initial sugestion for a dockerfile:

```Dockerfile
FROM python:3.9

USER root

RUN apt-get -y update && apt-get install python3-pip -y
RUN groupadd -r user && useradd -r -g user mne-user

RUN mkdir -p /home/mne-user/work
RUN mkdir -p /home/mne-user/data
RUN chown mne-user /home/mne-user
RUN chown mne-user /home/mne-user/work
RUN chown mne-user /home/mne-user/data
VOLUME ["/home/mne-user/work", "/home/mne-user/data"]

USER mne-user
WORKDIR ~/work
RUN pip install mne
RUN pip install -r https://raw.githubusercontent.com/mne-tools/mne-bids-pipeline/main/requirements.txt
ENTRYPOINT python -c "import mne; mne.sys_info()" && /bin/bash
```

This is not the insallation suggested in the documentation, but I couldn't get conda working its environments while building docker images. This installation should be cleaner anyway. I chose python's container, which is 916 MB. After this installation the MNE container is 2.59GB. MNE's install is large anyway.

**Comment by hoechenberger** [comment]
Hello @abcsds, this is a good start, thanks!

- I'd suggest to use the official MNE installers instead, on a Debian or Ububtu base image.
- You forgot to actually fetch the pipeline repository :)

**Comment by abcsds** [comment]
Hi @hoechenberger,
Thanks for picking it up. I sent the PR.

**Comment by larsoner** [comment]
Closing for https://github.com/mne-tools/mne-docker/issues/24
