### ISSUE TITLE
BUG: MEG+EEG?

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-bids-pipeline#601]
I just tried doing:
```
ch_types = ['meg', 'eeg']
```
and got
```
ValueError: EEG data can only be analyzed separately from other channel types. Please adjust `ch_types` in your configuration.
```
Is it not possible to analyze M/EEG data jointly?

**Comment by hoechenberger** [comment]
Nope, currently we only allow analysis of one channel type at a time IIRC

**Comment by larsoner** [comment]
As a first approach it seems like if multiple are listed, you enumerate over them for sensor analyses and for source analyses, plus in source analysis you do a joint one (at least if meg and eeg are in the list). WDYT?

**Comment by hoechenberger** [comment]
Yes, we should do that. This would then have to live in `run.py`, right?

**Comment by agramfort** [comment]
I don't like the idea of looping in run.py as it will produce 2 epochs
cleaned etc. Each derivative will be duplicated.

For example with the sample data that has meg and eeg in the same fif file.
Can we just process them jointly?

**Comment by hoechenberger** [comment]
Processing them jointly will require quite some refactoring in various places but it seems like the cleanest and most desirable approach to me indeed. Let's start working on this in a draft PR and add one processing step at a time and ensure it works.

**Comment by larsoner** [comment]
Some steps we might want to do some sort of loop. I have found it useful to have separate MEG, EEG, and M/EEG inverses for example to diagnose noise and/or rank issues. But we could start with a joint processing all the way through first.

**Comment by hoechenberger** [comment]
Yes, let's either make one PR per script or one per "step" (preprocessing, sensor, source) to keep the diffs small, WDYT?

**Comment by larsoner** [comment]
I'm not sure how that would work. My plan was to enable `ch_types = ['meg', 'eeg']`, see what broke, and fix it one by one. I'm not sure how we could make the PRs one by one very easily/meaningfully while getting feedback from CIs that we can trust

**Comment by larsoner** [comment]
... so in the end it would all be done in a single PR.

I think the review burden would be the same because each "one thing that needs to be fixed" should essentially be one file/script anyway
