### ISSUE TITLE
MAINT: Speed up ERP CORE runs

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-bids-pipeline#602]
They [take a while](https://app.circleci.com/pipelines/github/mne-tools/mne-bids-pipeline/3142/workflows/de070ac0-5b7d-4d15-b9fd-e0586990af2f):

<img width="294" alt="Screen Shot 2022-09-10 at 3 51 02 PM" src="https://user-images.githubusercontent.com/2365790/189499663-cecc7ea0-6890-401d-8d5e-b972de44a41c.png">

And about 15 minutes in one run is spent on time-by-time decoding:

<img width="768" alt="Screen Shot 2022-09-10 at 3 57 29 PM" src="https://user-images.githubusercontent.com/2365790/189499864-3fb0a3e6-3a57-4d91-b9ee-8ccd41627486.png">

@hoechenberger have you optimized these for run time already? If not, I might try cropping runs, decimating epochs, etc. Also for decoding across time:

https://mne.tools/mne-bids-pipeline/settings/sensor/statistics.html#config.decoding_time_generalization

We could perhaps add a `decoding_time_generalization_decim` which would be an *additional* decimation factor (on top of the `decim` used when creating epochs) to apply. In general the across-time stuff is fairly smooth:

https://mne.tools/mne-bids-pipeline/examples/ERP_CORE/sub-015_ses-N400_task-N400_report.html

So decimating by a factor of 2 or 4 would get us a squared-factor (i.e., 4x or 16x) speedup.

**Comment by hoechenberger** [comment]
Hello, I have done no optimizations here I believe. I'm not sure jow indeed about a new decimation parameter -- this would add yet another layer of decimation on top of epochs decimation. I'm not sure if we actually want to have this level of abstraction?

**Comment by larsoner** [comment]
FWIW I often do this when actually analyzing data using this technique. For publications you wouldn't need to but for sanity checks it's plenty good enough to get a sense of the data.

**Comment by agramfort** [comment]
+1 to introduce decoding_time_generalization_decim

**Comment by hoechenberger** [comment]
Ok, then let's try it. Decimation by a factor of 2 should reduce processing time to about 1/4th, right?

**Comment by agramfort** [comment]
yes something like this

**Comment by hoechenberger** [comment]
Let's do it and see how it flies. But please let's make sure we clearly add a note to the caption of the respective plots, stating that the data was decimated.

**Comment by larsoner** [comment]
BTW we should also go from a bunch of `tight_layout()` calls to just `fig.subplots(constrained_layout=True)`. So far in my couple of years of using it for many plots, it has always optimally used space, so I'm optimistic it will make things at least as good as they are currently (hopefully better in at least some cases).
