### ISSUE TITLE
MAINT: Proposed minor reorg

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-bids-pipeline#616]
Looking through the scripts, I notice a couple of things I'd like to reorganize. Proposal:

1. Rename `source/_03_make_cov.py` -> `sensor/_05_make_cov.py`. Covariances are useful for more than just source space -- I've used them for `plot_white` and decoding (`XDawn`) as well before doing any source analyses. They are not dependent in any way on any source space "stuff" (bem/trans/fwd/inv).
2. Move BEM solution computation from `source/_02_make_forward.py` to `source/_01_make_bem.py` (renamed from `source/_01_make_bem_surfaces.py`. In general the BEM surface <-> BEM solution relationship should be 1:1 (the second completely dependent on the first, and should be consistent with it). The forward step depends on the solution only (not the surfaces alone) so it makes sense to separate it.

If this sounds reasonable I can implement it in https://github.com/mne-tools/mne-bids-pipeline/pull/615

**Comment by larsoner** [comment]
And another:

4. Separate the source space setup step into `source/_02_setup_source_space.py` from the rest of the forward computation (renamed `source/_03_make_forward.py`). The forward pulls together information from a few different places:
    1. `info`, which can change for example if you set `destination` differently in `maxfilter`
    2. `trans`, which can change if you adjust your coreg params
    3. Various options that a user might decide to tweak (like `mindist`)
    3. `bem`, which generally does not change (and if it does, does so in the `make_bem` step)
    4. `src`, which generally does not change (and if it does, does so because the freesurfer recon changed)

    By keeping the `src` creation and saving with the `fwd` computation, we force somewhat slow recomputation of something that does not generally need to change (`src`, and without (2) above, `bem`) if any of the above change. By splitting it into

**Comment by larsoner** [comment]
> If this sounds reasonable I can implement it in https://github.com/mne-tools/mne-bids-pipeline/pull/615

Looking at the scope of the proposal, I think a separate PR actually makes more sense here. There is going to be a lot of code copy-paste into new files potentially, and it's nice if it's pure copy-paste as much as possible and not anything new. Then more caching can continue.

**Comment by agramfort** [comment]
sounds good to me

**Comment by hoechenberger** [comment]
Please do go ahead @larsoner
