### ISSUE TITLE
DOC: steps.md is out of date

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-bids-pipeline#617]
https://mne.tools/mne-bids-pipeline/features/steps.html

We should add to `tests/test_documented.py` that each script name appears in that doc, see it fail (TDD), and then fix it. Probably after https://github.com/mne-tools/mne-bids-pipeline/issues/616 so it's not immediately wrong.

**Comment by larsoner** [comment]
... and these numbers / order should match the top of each script, e.g. for `_03_make_forward.py`:
```
"""
====================
10. Forward solution
====================

Calculate forward solution for MEG channels.
"""
```
Or maybe better, we should get rid of the numbers at the top of scripts, since it's in the filename.

**Comment by agramfort** [comment]
+1 to remove numbers in headers
