### ISSUE TITLE
"decim" information in axis label isn't always rendered correctly

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#624]
I think this was introduced in #603.

- Sometimes the information is just cut off:
  <img width="619" alt="Screen Shot 2022-10-07 at 11 09 05" src="https://user-images.githubusercontent.com/2046265/194518098-20d9bb2b-336f-49bd-8f88-161001e3b1f4.png">
- Sometimes it's displayed as an array (?):
  <img width="644" alt="Screen Shot 2022-10-07 at 11 09 14" src="https://user-images.githubusercontent.com/2046265/194518250-c5ca3cf3-f25e-4378-a671-17adff9646f5.png">

(Examples are from https://output.circle-artifacts.com/output/job/e043e4f2-7911-4df9-bd5c-08e0b37933f9/artifacts/0/site/examples/ERP_CORE/sub-average_ses-P3_task-P3_report.html)

Generally, I think the decim information should be placed in the same line as the rest of the axis label.

cc @larsoner

**Comment by larsoner** [comment]
My preferred solution would be to use constrained layout, it should automatically fix this. I think we should do it regardless of where decim shows up

**Comment by larsoner** [comment]
Fix pushed to #622
