### ISSUE TITLE
BUG: Handling of rest and empty-room

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-bids-pipeline#632]
Naively I would have expected that if there are empty room and/or resting state runs in a dataset, they would be analyzed regardless of what the plan is for `noise_cov` during inversion. Thinking about things like connectivity analyses + evoked analyses on the same dataset with the same processing this makes the most sense.

But in the code we have logic like (here for the `frequency_filter` step):
```
    if (cfg.process_er or config.noise_cov == 'rest') and run == cfg.runs[0]:
        noise_task = "rest" if config.noise_cov == "rest" else "noise"
        if cfg.use_maxwell_filter:
            raw_noise_fname_in = bids_path_in.copy().update(
                run=None, task=noise_task
            )
            in_files["raw_noise"] = raw_noise_fname_in
            _update_for_splits(in_files, "raw_noise", single=True)
        else:
            if config.noise_cov == 'rest':
                in_files["raw_rest"] = bids_path_in.copy().update(
                    run=None, task=noise_task)
            else:
                assert config.noise_cov == 'noise'
                ref_bids_path = bids_path_in.copy().update(
                    run=cfg.mf_reference_run,
                    extension='.fif',
                    suffix='meg',
                    root=cfg.bids_root,
                    check=True
                )
                in_files["raw_er"] = ...
```
... which is complicated, to say the least. There is even a bug hidden by non-covered test lines here, because `assert noise_cov == 'noise'` should be `assert noise_cov == 'emptyroom'`. And I think `noise_cov = 'ad_hoc'` is not addressed properly here, either!

I propose we change this to a much simpler scheme like:
```
if has_empty_room:
    in_files['raw-noise'] = ...
if has_resting_state:
    in_files['raw-rest'] = ...
```
This can be implemented at the maxwell filtering stage and the frequency filtering stage. Then the logic about what to use for `noise_cov` + `inverse` only lives in those functions -- and when the param is changed, it only changes those functions.

**Comment by larsoner** [comment]
... and if a dataset has empty-room and resting-state, but someone *really* does not want them processed, we can add a `ignore_empty_room` and/or `ignore_resting_state`. But I'd assume YAGNI on this, especially now that we have caching... it's not going to make stuff take that much longer for most people I think.

**Comment by agramfort** [comment]
👍
