### ISSUE TITLE
Use flake8-pyproject

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#636]
This will allow us to move the flake8 config options from the makefile to pyproject.toml

See
https://github.com/john-hen/Flake8-pyproject/issues/2

**Comment by larsoner** [comment]
@hoechenberger WDYT about just switching to `black` instead?

Not sure the best infrastructure -- pre-commit hook, auto-formatting GH action that pushes commits, ... ?

**Comment by drammock** [comment]
pydata-sphinx-theme uses black with a pre-commit hook and I like it. It took maybe 2-3 commits to get used to and after that it was seamless.

**Comment by hoechenberger** [comment]
I like black, let's do this. But it cannot fully replace flake8, as it's just for formatting...
