### ISSUE TITLE
BUG: installation guide in the documentation page 

### ISSUE THREAD

**Issue by dissagaliyeva** [mne-tools/mne-bids-pipeline#637]
#### Description of the problem

When I started looking into the package to run the example [M/EEG conversion pipeline](https://mne.tools/mne-bids-pipeline/examples/ds000248.html), I ran into multiple issues such as:

[Installation page](https://mne.tools/mne-bids-pipeline/getting_started/install.html):
- [Installation instructions](https://mne.tools/mne-bids-pipeline/getting_started/install.html#install-the-mne-bids-pipeline) are outdated (the link is broken)
- The link under the `Installation` note is also broken: `pip install https://github.com/mne-tools/mne-bids-pipeline/archive/refs/heads/main.zip` 

[Basic usage](https://mne.tools/mne-bids-pipeline/getting_started/basic_usage.html#adjust-your-configuration-file):
- After copying and supplementing the config.py file, I couldn't run the script. After googling for a bit, I found out that we need to remove everything under `custom configuration ends here`. It would be great to add it to the documentation page as well!
- For some reason, I couldn't run this command: `mne_bids_pipeline --config=/path/to/your/custom_config.py`. Instead, I was able to do so using `python run.py --config custom_config.py`. 

Please let me know what you think about it so I can submit a PR request :)

**Comment by hoechenberger** [comment]
Hello @dissagaliyeva, thanks for reporting. We will update the installation instructions soon.

Best wishes,
Richard

**Comment by larsoner** [comment]
Working on this now...
