### ISSUE TITLE
Any thoughts about nipype?

### ISSUE THREAD

**Issue by bloyl** [mne-tools/mne-bids-pipeline#64]
This seems like an interesting and potentially useful project.

I'm curious if there was any thought to making a nipype (https://nipype.readthedocs.io/en/latest/) type interfaces?

I don't use nipype very often but I have found it useful in the past to standardize some large batch processing. Just a thought.

**Comment by larsoner** [comment]
And maybe https://neuropycon.github.io/ephypype/ to make it easy to use `nipype` for these tasks?

**Comment by jasmainak** [comment]
It would be great if you can try this on CTF data to identify potential pain points in using this. I suggested the same to @AdoNunes 

as for neuropycon, give it a try but maybe joblibs does the job already and you don't need caching.

**Comment by agramfort** [comment]
what would be the benefit of nipype? our current approach is pure python so
no need to mix languages and packages.
I find our approach simple in understanding what we pass as input and get
as output

**Comment by bloyl** [comment]
What I think nipype has to offer is scalability, flexibility and sharing, but that comes at the expense of some of the simplicity and clarity.

Some of the things I think are nice about nipype are its
1) workflow visualization/diagrams (see the middle bottom of https://miykael.github.io/nipype_tutorial/notebooks/example_preprocessing.html)
2) workflow hotstarts in the event of errors etc.
3) optional overwriting etc. controlled at the workflow level.
4) sharability: if the nodes here were in nipype I could just use them.
5) its a robust pipelining tool - why invent another one?

Also it seems like someone is supporting the mne-c and mne-pthon function calls (https://github.com/nipy/nipype/issues/3032)

Like i said before I don't really use nipype but it is something that i think i would use if the barrier to entry was alittle bit lower.

**Comment by agramfort** [comment]
I stay open but I feel this is premature here. We have something that works
and that needs to be consolidated. Once we have a stable code/solution why
not looking into different strategies.

>

**Comment by jasmainak** [comment]
has anybody looked into doit: https://pydoit.org/ ?

**Comment by larsoner** [comment]
I think we have decided to use joblib caching at this point so I'll close
