### ISSUE TITLE
ENH: Improve report generation and caching

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-bids-pipeline#648]
Currently the flow is: run all steps, then generate report. An alternative equivalent flow is: run each step, and within each step, add to the report any relevant/updated information.

Changing to this new flow will make report generation *much faster*, because sections only need to be updated/reproduced when things in them actually change. In other words, we get caching for free by piggybacking report generation within individual steps. It also helps with namespaces / encapsulation because it's easier to see/know what needs to go and be used in each report section. If you add something new to a given step -- or want more information from it in the report -- the relevant report code now lives in the given step, rather than in the monolithic `_01_make_report.py`.

In practical terms, I think this "just" requires using the Report save/load functionality to persist sections to disk (and save/write the HTML at the conclusion of each step, which should be fast enough), and then moving a bunch of code lines to the correct scripts. I think as long as we use the correct/consistent section names. And then hopefully `_01_make_report.py` goes away completely. At least in principle I think this is all that will be necessary.

**Comment by hoechenberger** [comment]
This is exactly what @agramfort and I had discussed a few times and it's what we want to have. So +100 from my end to add this
