### ISSUE TITLE
Switch from optparse to argparse

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#656]
> Deprecated since version 3.2: The [optparse](https://docs.python.org/3/library/optparse.html#module-optparse) module is deprecated and will not be developed further; development will continue with the [argparse](https://docs.python.org/3/library/argparse.html#module-argparse) module.

https://docs.python.org/3/library/optparse.html

**Comment by larsoner** [comment]
Done in #658
