### ISSUE TITLE
Deprecate MNE_BIDS_STUDY_* env vars in favor of MNE_BIDS_PIPELINE_*?

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#659]
The `MNE_BIDS_STUDY_*` environment variables are essentially leftovers from the days when this project was called the MNE-BIDS Study Template.

However, `MNE_BIDS_PIPELINE_*` is suuuuper long, so I'm not sure if we really want that either…

**Comment by larsoner** [comment]
I don't think any users are meant to use these anyway, just interact via config. So really they should probably be `_MNE_BIDS_PIPELINE_*`

**Comment by hoechenberger** [comment]
I'm wondering if we actually need environment variables at all, can we somehow do without them? I know they are extremely versatile but I'm always concerned about unintended side effects. What is your feeling on this? I'd prefer to explicitly pass around function parameters instead of environment variables.

**Comment by larsoner** [comment]
Agreed it would be nice to avoid these. I think in principle it should be possible, I'll take a look
