### ISSUE TITLE
Cut a release

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#660]
We should cut a 2022.11.0 release, or 0.1.0 if we cannot agree on CalVer (although I think the pipeline would be a prime example of a project with rolling releases and hence CalVer would totally make sense)

We should set up machinery like for openneuro-py, where tagging a new release triggers a build and upload to PyPI

We can then also create a conda-forge package and include it in the MNE installers

**Comment by agramfort** [comment]
+1

**Comment by hoechenberger** [comment]
I will start working on this

**Comment by drammock** [comment]
> We should cut a 2022.11.0 release, or 0.1.0 if we cannot agree on CalVer

I thought this was settled. We discussed this at length at a dev meeting several weeks ago, and IIRC it was 3-to-1 in favor of semver. Why are you bringing it up again here?

**Comment by hoechenberger** [comment]
I don't think we discussed it for the pipeline, only for MNE, no? We're constantly breaking ... everything here, I just don't see a point in having SemVer here

**Comment by hoechenberger** [comment]
But if you say we already settled in something then I don't want to reopen the discussion of course 

I still think SemVer is useless here

**Comment by drammock** [comment]
> I don't think we discussed it for the pipeline, only for MNE, no?

I'm fairly sure you are misremembering. If you had been suggesting that we change the MNE-Python versioning system then I'm even more strongly opposed than I expressed at that meeting.

**Comment by hoechenberger** [comment]
I just realized one cannot "pre-register" a package name on PyPI, so I would suggest we do the first release "manually" (tagging, building packages, publishing to PyPI), and afterwards we set up a CI task to automate this process in the future. Thoughts? Am I overlooking something?

**Comment by hoechenberger** [comment]
> I'm fairly sure you are misremembering.

Very well possible! Too much going on for my brains to handle at the moment 🤯 Sorry about the confusion!

**Comment by larsoner** [comment]
WDYT about renaming `scripts/*` to `steps/*`? I can do that after #663 (which eradicates env vars), and I tagged a couple of other things for 0.1 that I think we can get done by Nov 30, which I set for the milestone date:

https://github.com/mne-tools/mne-bids-pipeline/milestone/1

Then we can hopefully cut a MNE 1.3 sometime in December that includes it. That way 2023 will be year of MNE-BIDS-Pipeline :)

**Comment by agramfort** [comment]
👍

**Comment by hoechenberger** [comment]
Sounds good to me!

**Comment by larsoner** [comment]
I'm thinking 1.0.0 might be the most appropriate number for the release based on how semantic versioning is meant to work. I don't think we need to be as conservative as MNE-Python on this front.

@hoechenberger okay for me to release a 0.1 now on PyPI so we can ensure the release infrastructure is working? Then once these last few PRs are merged we can cut 1.0.0.

**Comment by hoechenberger** [comment]
Why don't you do a 1.0 pre-release instead?

https://peps.python.org/pep-0440/#pre-releases

_(I still think this project will only ever do rolling releases so SemVer is useless but be it as it may...)_

**Comment by hoechenberger** [comment]
> Why don't you do a 1.0 pre-release instead?

But of course 0.1 is ok too if that makes things easier for you

**Comment by larsoner** [comment]
automated release appears to have worked

https://pypi.org/project/mne-bids-pipeline/1.0.0/
