### ISSUE TITLE
CSP results missing from reports in example gallery

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#661]
The ERP CORE example configuration requests decoding via CSP, but the reports don't seem to contain CSP, neither on the single-subject nor on the group level:

https://mne.tools/mne-bids-pipeline/examples/ERP_CORE.html

**Comment by larsoner** [comment]
The ERN task has it at least for 15, which seems correct. Feel free to close

**Comment by hoechenberger** [comment]
Ooooh you're right, it was only requested for ERN! I misread the configuration! Closing
