### ISSUE TITLE
MAINT: Website is huge

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-bids-pipeline#682]
On account of this
```shell
~/python/mne-bids-pipeline/docs/source/examples$ du -hs
1.3G	.
~/python/mne-bids-pipeline/docs/source/examples$ ls -al ds000248_base
total 108516
drwxrwxr-x  2 larsoner larsoner     4096 Dec  6 12:20 .
drwxrwxr-x 20 larsoner larsoner     4096 Dec  7 09:35 ..
-rw-rw-r--  1 larsoner larsoner 64233835 Dec  6 16:27 sub-01_task-audiovisual_report.html
-rw-rw-r--  1 larsoner larsoner 46865524 Dec  6 16:27 sub-average_task-audiovisual_report.html
```
We should find a way to make the reports smaller.

**Comment by hoechenberger** [comment]
I had been experimenting with SVG, different compression levels etc a while back and didn't find a good solution while preserving decent image quality. Would be great to investigate again

**Comment by larsoner** [comment]
Did you try just PNG for the Evokeds? IIRC the multi-channel `evoked.plot` plots take a ton of space for SVG but are okay for PNG

**Comment by hoechenberger** [comment]
I don't remember honestly ...
