### ISSUE TITLE
Try out ruff?

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#686]
As a replacement for flake8:

https://pypi.org/project/ruff/

WDYT @larsoner?

**Comment by drammock** [comment]
that looks very promising; would be awesome to have a linter fast enough to be used as a commit hook.  Off the top of my head though I think it at least lacks `flake8-array-spacing` functionality (which MNE-Python uses, not sure if the pipeline does).  Might still be possible to adopt it though.

**Comment by larsoner** [comment]
IIRC the array spacing one is barely used, and will definitely go away if we adopt black like we plan to do at some point (at least I think we converged on this). It might be worth getting rid of it and just reformatting or noqa'ing where it made a difference

**Comment by agramfort** [comment]
if I can have a faster linter output on save in vscode that is much
appreciated :)

**Comment by larsoner** [comment]
Done in #688

**Comment by hoechenberger** [comment]
> if I can have a faster linter output on save in vscode that is much
> appreciated :)
> 
> > Message ID: ***@***.***>
> >
> 

I believe they are actually working on an extension for VS Code so you wouldn't even have to install ruff into your Python environment anymore. I can keep you posted on this.

**Comment by hoechenberger** [comment]
> > if I can have a faster linter output on save in vscode that is much
> > appreciated :)
> > 
> > > Message ID: ***@***.***>
> > >
> > 
> 
> I believe they are actually working on an extension for VS Code so you wouldn't even have to install ruff into your Python environment anymore. I can keep you posted on this.

Oh it's already available, see: https://devblogs.microsoft.com/python/python-in-visual-studio-code-december-2022-release/#community-highlight-ruff
