### ISSUE TITLE
Rename N_JOBS parameter to n_jobs

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#694]
For consistency, it should be lowercase.

**Comment by larsoner** [comment]
Agreed, the all-uppercase always seemed odd. And I also got it wrong in a config before since it's lowercase in MNE-Python

**Comment by larsoner** [comment]
... maybe in a 1.0.3 (or whatever number we're on now?) since we still haven't announced + distributed? I'll make a quick PR today so it can make it into the installers for MNE 1.3

**Comment by larsoner** [comment]
Fixed by #696
