### ISSUE TITLE
"joblib" directory in output folder

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#723]
I'm getting a "joblib" folder in my derivatives directory. Is this intended behavior? if so, could we make it "hidden" (prefix with a `.`)?

PS wanted to upload a screenshot but somehow it's not working

**Comment by agramfort** [comment]
yes and I would say no

it can fill up your disk and you won't see it easily if you hide the folder

now we could call it something more meaninful in our context
