### ISSUE TITLE
Switch from coloredlogs to rich

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#726]
Coloredlogs seems pretty much dead – last commit almost 2 years ago:
https://github.com/xolox/python-coloredlogs

A well-maintained, extremely popular, and more versatile alternative is rich:
https://github.com/Textualize/rich

We should consider switching our logging system to rich

It can even render tracebacks beautifully:

![](https://github.com/textualize/rich/raw/master/imgs/traceback.png)

Thoughts?

**Comment by agramfort** [comment]
no objection

**Comment by larsoner** [comment]
That would be great, coloredlogs was a pain to get working properly with parallelization
