### ISSUE TITLE
Add version info to mne-bids-pipeline

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-bids-pipeline#728]
> it would be helpful if the version of the bids-pipeline used per step was to be found in the output for reporting in a paper and replicability

_Originally posted by @SophieHerbst in https://github.com/mne-tools/mne-bids-pipeline/issues/609#issuecomment-1482981862_

**Comment by larsoner** [comment]
... I thought at some point we had `mne.sys_info()` output in there, but looking online I don't see it e.g. here

https://mne.tools/mne-bids-pipeline/1.2/examples/ds004229/sub-102_task-amnoise_report.html

We should `lru_cache` the output string

**Comment by hoechenberger** [comment]
> ... I thought at some point we had `mne.sys_info()` output in there, but looking online I don't see it e.g. here

It probably got lost somewhere, it used to be included.

But I don't think men-bids-pipeline is listed in mne.sys_info(), or is it? If it isn't, we should add it upstream
