### ISSUE TITLE
Add command line option for deriv_root

### ISSUE THREAD

**Issue by vferat** [mne-tools/mne-bids-pipeline#772]
As I develop a Docker App using mne-bids-pipeline, I want a straightforward way to overwrite the bids_root and deriv_root values defined in the configuration file from the command line. This enhancement aims to simplify Docker volume mapping.

Currently, the option to override `bids_root `is already available ([source](https://github.com/mne-tools/mne-bids-pipeline/blob/ea95979fdb0ef807b3cd262da409cf010ada3da3/mne_bids_pipeline/_main.py#L56)), but there is no similar option for `deriv_root`.

I suggest adding a command-line option to the mne-bids-pipeline tool to allow users to specify the deriv_root directory. This behavior is similar to other BidsApps such as `FMRIprep `and `MRIQC`, where command line arguments overwrite configuration files.

If you are interested, I would be happy to contribute by taking care of the pull request.

**Comment by larsoner** [comment]
Makes sense to me, PR welcome!
