### ISSUE TITLE
Release 1.5.0

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#783]
@larsoner Looking at the list of changes since the last release, I believe a new one is already overdue. LMK if you agree, and I'll cut a new release

**Comment by larsoner** [comment]
Sure but let's wait maybe a week to make sure the BIDS naming stuff is okay and we don't have issues with https://github.com/mne-tools/mne-python/pull/11903

**Comment by hoechenberger** [comment]
I don't see how this PR pertains to the pipeline..? 🤔

**Comment by larsoner** [comment]
See top comment of the PR:

> <img width="768" alt="Screenshot 2023-08-19 at 5 03 39 PM" src="https://github.com/mne-tools/mne-bids-pipeline/assets/2365790/36ff1c0b-f088-4cce-8dd7-289f61861162">

**Comment by hoechenberger** [comment]
I still don't follow, the FIFF changes would only go into the next MNE release, no? So it won't affect the pipeline when working with MNE 1.5.0

**Comment by larsoner** [comment]
Safer to fix them now in case we don't release a new version here before MNE 1.6 comes out

**Comment by larsoner** [comment]
I checked and it looks like we're okay, feel free

**Comment by larsoner** [comment]
@hoechenberger want me to cut 1.5?

**Comment by hoechenberger** [comment]
We should address #796 first

**Comment by hoechenberger** [comment]
@larsoner
Please feel free to cut a release, I don't think I'll have time in the foreseeable future … And I really think we should have a release, it's too many changes that have accumulated already since 1.4!

**Comment by larsoner** [comment]
Okay I cut https://github.com/mne-tools/mne-bids-pipeline/releases/tag/v1.5.0, feel free to adjust the notes and title etc. if you want @hoechenberger . I just took the generated changelog and removed the pre-commit bot PRs.
