### ISSUE TITLE
Name conflict in typying.py

### ISSUE THREAD

**Issue by SepehrRezaee** [mne-tools/mne-bids-pipeline#794]
I tried to clone the[ "mne-bids-pipeline" ](https://github.com/mne-tools/mne-bids-pipeline)repository alongside of my project and use the [mne-bids-pipeline](https://github.com/mne-tools/mne-bids-pipeline/tree/main)/[mne_bids_pipeline](https://github.com/mne-tools/mne-bids-pipeline/tree/main/mne_bids_pipeline)
folder. But when I run the mne_bids_pipeline/_run.py file in the [mne-bids-pipeline](https://github.com/mne-tools/mne-bids-pipeline/tree/main)/[mne_bids_pipeline](https://github.com/mne-tools/mne-bids-pipeline/tree/main/mne_bids_pipeline)
/_run.py address, I get **a naming conflict error**. 
The reason is the existence of a file called [typing.py](https://github.com/mne-tools/mne-bids-pipeline/blob/main/mne_bids_pipeline/typing.py) in [mne-bids-pipeline](https://github.com/mne-tools/mne-bids-pipeline/tree/main)/[mne_bids_pipeline](https://github.com/mne-tools/mne-bids-pipeline/tree/main/mne_bids_pipeline) , which has the same name as Python's [typing module](https://docs.python.org/3/library/typing.html).
I wanted to report this.
Thanks for your attention

**Comment by hoechenberger** [comment]
Hello, thanks for reporting this. 

Please note that the pipeline should be run via the `mne_bids_pipeline` command line interface. 

Best wishes,
Richard

**Comment by SepehrRezaee** [comment]
Hello Mr @hoechenberger,

Thank you very much for your important note and also for your attention

Best regards,
Sepehr

**Comment by hoechenberger** [comment]
You are most welcome! Please do feel free to post here or on the MNE forum if you have any other questions. We appreciate your feedback!

**Comment by SepehrRezaee** [comment]
Thank you so much for your warm welcome! I will definitely keep that in mind and reach out if I have any further questions. Your appreciation for feedback is greatly appreciated as well.
