### ISSUE TITLE
select and reject ICA components

### ISSUE THREAD

**Issue by SophieHerbst** [mne-tools/mne-bids-pipeline#8]
Right now `04-artifact_correction_ica.py` just runs the ICA but doesn't do anything with it. 
We need a new scripts to visualize and select the components: 
https://mne-tools.github.io/stable/auto_tutorials/plot_artifacts_correction_ica.html

and to reject them

```py
ica.apply(realData, exclude=exclude_ICA) 
```

**Comment by SophieHerbst** [comment]
@agramfort: can we look at how you would select ICA components when we meet next Tuesday? I can make a suggestion, but I am not fully satisfied with how I am doing it right now.

**Comment by agramfort** [comment]
ok or ping me on hangout

>

**Comment by SophieHerbst** [comment]
Hi again!
I am putting together an ICA-rejection script (I'll need it for my student). 
@agramfort – is there any way to run create_ecg_epochs on epochs data?
Otherwise I will have to load  the raws from all runs again to do this, which takes a lot of memory.

**Comment by agramfort** [comment]
no as ecg epochs are based on ecg peaks as events. I would recommend
to use only one maxfiltered run. It should be more than enough to have
a good number of ecg epochs. The alternative is to use epochs but to
keep the ECG channel in the epochs and detect ECG ICA sources by
correlation which may work. It would require some work and would take
a weeks or more to do. I would go with one raw object.

**Comment by hoechenberger** [comment]
Closing, automated artifact rejection is working now and ICs selected for rejection can be reviewed and adjusted manually.

**Comment by SophieHerbst** [comment]
haha, that was a really old one!

**Comment by hoechenberger** [comment]
Yes, at least after 5 years we could finally close it! It's almost done with pre-school :)
