### ISSUE TITLE
Add on option to use "un-cleaned" epochs for decoding (omitting ICA / SSP)

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#808]
My sense is that things like SSP and ICA probably won't matter but that peak-to-peak rejection could help, depending on the nature of the artifacts. That sounds in line with what you're seeing @hoechenberger . In this case it makes sense for us to use the "clean" epochs for decoding. At some point we could make it an option which to use (but maybe assume YAGNI for now?)

_Originally posted by @larsoner in https://github.com/mne-tools/mne-bids-pipeline/issues/796#issuecomment-1789318605_

**Comment by hoechenberger** [comment]
@larsoner I may be able to make a PR for this tonight or tomorrow. We can then cut a release and include 1.5 in the installer. 

Q: should we jump to 1.6 directly to match the MNE version?

**Comment by larsoner** [comment]
I don't think we should try to match the MNE version. Maybe in this project we can take SEMVER seriously and make it 2.0. I'm sure we have a breaking change in here somewhere :)

**Comment by hoechenberger** [comment]
I'm still a big fan on date-based versioning but if that's off the table still, I'm all for serious SemVer like you proposed, even if that means jumping to version 13 by the end of next year or so
