### ISSUE TITLE
_bads.tsv missing for reference run (preprocessing/_03_maxfilter)

### ISSUE THREAD

**Issue by SophieHerbst** [mne-tools/mne-bids-pipeline#842]
Sorry, another issue: 
It seems like the pipeline wants an extra file for the bad channels for the reference run, but in my BIDS dataset, bad channels are marked in the channels.tsv files for each run, and I don't have the _bads.tsv file
Is there a parameter I am missing to use this file?
Thanks!

```
┌────────┬ preprocessing/_03_maxfilter ─────────────────────────────────────────
│16:57:50│ ❌ sub-155 run-01 A critical error occurred. The error message was: missing in_files["raw_ref_run-bads"] = /neurospin/meg/meg_tmp/TimeInWM_Izem_2019/BIDS_anonymized/derivatives/mne-bids-pipeline/sub-155/meg/sub-155_task-tiwm_run-01_bads.tsv

Aborting pipeline run. The traceback is:

  File "/home/sh254795/Documents/REPOS/mne-study-template/mne_bids_pipeline/_run.py", line 412, in _path_to_str_hash
    assert v.exists(), f'missing {kind}_files["{k}"] = {v}'
```

**Comment by larsoner** [comment]
This is on latest `main`? And on a new/clean run of the data (with derivatives deleted)?

There are some complicated conditionals about when to add bads and where they come from. It's possible there is an error in the logic somewhere. Any chance you can share one subject's data and a config file with me privately that I can use to reproduce the error?

**Comment by SophieHerbst** [comment]
Hi @larsoner, I confirm, no existing derivatives when starting the pipeline, and latest main. I will send you a link. Thanks!
