### ISSUE TITLE
Review ICA report logic

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#864]
This can maybe be tackled as part of #857

But I just came across this code:

https://github.com/mne-tools/mne-bids-pipeline/blob/61b35530b16a61753b25fa663b575d9b2f7a6ed5/mne_bids_pipeline/steps/preprocessing/_08a_apply_ica.py#L162-L202

And I don't quite understand why we might end up writing the report twice here? Am I missing something?

(FWIW in my last pipeline run I only see an "Effects of ICA cleaning" section)

**Comment by larsoner** [comment]
I agree that looks like a bug and that we should always just `add_ica` in a `_open_report` context, so delete these custom lines and remove the skip
