### ISSUE TITLE
Align report sections with pipeline steps

### ISSUE THREAD

**Issue by SophieHerbst** [mne-tools/mne-bids-pipeline#880]
I think the epochs should be after the ICA cleaning, to reflect the order of processing steps, no?

![Capture d’écran du 2024-03-08 15-34-50](https://github.com/mne-tools/mne-bids-pipeline/assets/6408073/e5c510f9-fd37-432f-bcb9-a38192c1a3e9)

**Comment by SophieHerbst** [comment]
In the same vein, I don't quite get the logic/ distinction between the three ICA-related reports: 
![Capture d’écran du 2024-03-08 15-42-20](https://github.com/mne-tools/mne-bids-pipeline/assets/6408073/06caf4b7-7cdc-435c-bab2-3bbb3c9bf151)

**Comment by larsoner** [comment]
> I think the epochs should be after the ICA cleaning, to reflect the order of processing steps, no?

So the order in the image is:
```
Epochs (before cleaning)
ICA
Epochs (after cleaning)
```
which I think is correct (though not complete, which is probably okay). ICA here is really meant to be "ICA components and artifact rejection" or similar. If you use SSP you get a similar order but SSP shows up where ICA is, basically saying "this is what was selected for removal".

In terms of what the pipeline actually does you could in principle do:
```
ICA fitting
ICA artifact identification
Epochs (before cleaning)
ICA application / artifact rejection
Epochs (after cleaning)
```
or so, but I'm not sure it would help readability too much.

> In the same vein, I don't quite get the logic/ distinction between the three ICA-related reports:

The `icafit` is from that initial fitting phase only. I can't remember what the other ones are offhand, but it can be pieced together from looking at their contents and also where they are generated for [icafit in _06a1](https://github.com/mne-tools/mne-bids-pipeline/blob/b52742e0b1a08deac963f59dafff4ad2d0578a62/mne_bids_pipeline/steps/preprocessing/_06a1_fit_ica.py#L85-L87), [ica+components in _06a2](https://github.com/mne-tools/mne-bids-pipeline/blob/b52742e0b1a08deac963f59dafff4ad2d0578a62/mne_bids_pipeline/steps/preprocessing/_06a2_find_ica_artifacts.py#L146-L148), and [ica in _08a](https://github.com/mne-tools/mne-bids-pipeline/blob/b52742e0b1a08deac963f59dafff4ad2d0578a62/mne_bids_pipeline/steps/preprocessing/_08a_apply_ica.py#L161-L184). Feel free to give it a shot and update the doc if you have time!

**Comment by hoechenberger** [comment]
_I think #845 is related to this_

**Comment by larsoner** [comment]
I didn't think #845 is related really, that has to do with parallelization and this more an issue of what reports do we want generated for ICA at all
