### ISSUE TITLE
Drop support for Python 3.9?

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#906]
I would love to drop support for Python 3.9, which would allow us to write types such as

```python
Optional[Union[str, float]]
```
as
```python
None | str | float
```
which is much more readable. I'm mostly thinking about the configuration file here, which is immediately user-facing.

Thoughts?

**Comment by larsoner** [comment]
Sure, 3.10 came out over 2 years ago and it's even within [SPEC0](https://scientific-python.org/specs/spec-0000/) to drop it:

![image](https://github.com/mne-tools/mne-bids-pipeline/assets/2365790/be72003e-5da0-48f3-942d-5bd4f7695c92)

**Comment by hoechenberger** [comment]
I don't like SPEC but I do like dropping old versions :D

I can take a stab at this next week if you want. Unless you insist on having a cozy Sunday afternoon project :)

**Comment by larsoner** [comment]
Feel free to tackle it whenever you get time, probably along with #907
