### ISSUE TITLE
Report section on original raw data doesn't contain bads

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#930]
In my BIDS data, 3 channels are marked as bad. These show up correctly in the HTML repr for the filtered and cleaned raw, but not for the original raw. The content of the generated `*_bads.tsv` file is:

```
name	reason
P8	pre-existing (before MNE-BIDS-pipeline was run)
T7	pre-existing (before MNE-BIDS-pipeline was run)
TP10	pre-existing (before MNE-BIDS-pipeline was run)
```

<img width="984" alt="Screenshot 2024-04-23 at 13 17 29" src="https://github.com/mne-tools/mne-bids-pipeline/assets/2046265/3ffc2d00-a723-4418-8c15-c06c52695671">

<img width="984" alt="Screenshot 2024-04-23 at 13 17 34" src="https://github.com/mne-tools/mne-bids-pipeline/assets/2046265/85e577b6-6abe-47f5-9ca2-2c6d63183379">

I tried to understand what was going on but so far I don't really have a clue.

**Comment by hoechenberger** [comment]
I also just realized that experimenter and participant are also not correctly represented in the "original" repr.

**Comment by hoechenberger** [comment]
@SophieHerbst Do you see similar issues with your reports?

**Comment by larsoner** [comment]
Are you fully up to date with your MNE version? If you're a couple weeks behind you might be hitting a bug that was in MNE for a bit

**Comment by hoechenberger** [comment]
everything's up to date and i had delayed the outputs entirely...

will check again to be sure

**Comment by hoechenberger** [comment]
> https://github.com/mne-tools/mne-python/pull/12548

that's not the problem, it is as of part of my raw.info is simply missing

**Comment by larsoner** [comment]
Sounds like the bads just aren't being loaded from the sidecar then. I bet bads aren't displayed in the info repr if the list is empty. And they probably aren't defined in the raw on disk itself but rather in the sidecar file

**Comment by hoechenberger** [comment]
> Sounds like the bads just aren't being loaded from the sidecar then.

Yep that's it. Looking into this now. Thanks for your help!
