### ISSUE TITLE
We're currently applying reject thresholds to ECG and EOG epochs used for ICA artifact detection, but I think we shouldn't

### ISSUE THREAD

**Issue by hoechenberger** [mne-tools/mne-bids-pipeline#939]
After ECG and EOG epochs construction, we seems to be applying the PTP rejection thresholds the user specified for "data channels":

https://github.com/mne-tools/mne-bids-pipeline/blob/7e1d9f91e3b127a13295536c495e56d133127059/mne_bids_pipeline/steps/preprocessing/_06a2_find_ica_artifacts.py#L190-L192

https://github.com/mne-tools/mne-bids-pipeline/blob/7e1d9f91e3b127a13295536c495e56d133127059/mne_bids_pipeline/steps/preprocessing/_06a2_find_ica_artifacts.py#L235-L237

I would intuitively think that we shouldn't do this, since it could effectively eliminate part of the very artifact we're trying to isolate here. But the code is there … and I suspect we put it in for a reason?

@larsoner @agramfort @SophieHerbst Any idea what to do about this?

**Comment by hoechenberger** [comment]
@larsoner Could it be that you added this during a recent refactoring? I just (super briefly) looked at the 1.5.0 code and I don't think we have this behavior there.

**Comment by SophieHerbst** [comment]
So epochs.reject just applies the previously selected drops thresholded with ica_reject?
That sounds right to me.

**Comment by hoechenberger** [comment]
Ok, let's leave it like this for now :) Thanks for your input, @larsoner and @SophieHerbst!
