### ISSUE TITLE
ValueError: Extension .xlsx is not allowed.

### ISSUE THREAD

**Issue by SophieHerbst** [mne-tools/mne-bids-pipeline#944]
I am trying to write a script to read the xlsx files generated in 
_05_decoding_csp.py

I copied and adjusted my code from the above script, 
but I get the following error: 
ValueError: Extension .xlsx is not allowed.

What am I missing?

```
fname_decoding = bids_path.copy().update(subject=subject,
                        session=None,
                        task=task,
                        datatype=datatype,
                        processing=processing, 
                        suffix="decoding", 
                        extension=".xlsx"
            )
```

I am on the latest stable for mne, mne-bids, and the pipeline.

**Comment by hoechenberger** [comment]
pass `check=False`, that should fix it
