### ISSUE TITLE
ENH: Type checking

### ISSUE THREAD

**Issue by larsoner** [mne-tools/mne-bids-pipeline#994]
@hoechenberger I saw in a recent PR that @drammock added some missing type hints. I am not very experienced with type checking but this repo seems pretty well documented -- worth adding `mypy` to pre-commit or at least a CI run? I briefly tried both `mypy` and `pyright` and `mypy` was a little bit faster and used already by MNE so I'm inclined to try that.

I already see some annoyingness with TypedDict not subclassing dict but I'll look into that if type checking does seem worthwhile.

**Comment by agramfort** [comment]
as the mne-bids-pipeline is not so easy to unit test, I can see some value
in type checking here. +1 for mypy
